// Code generated by ent, DO NOT EDIT.

package lotteryprizepoolcode

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the lotteryprizepoolcode type in the database.
	Label = "lottery_prize_pool_code"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRedeemCodeID holds the string denoting the redeem_code_id field in the database.
	FieldRedeemCodeID = "redeem_code_id"
	// FieldPrizeValue holds the string denoting the prize_value field in the database.
	FieldPrizeValue = "prize_value"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAssignedToUserID holds the string denoting the assigned_to_user_id field in the database.
	FieldAssignedToUserID = "assigned_to_user_id"
	// FieldAssignedDrawRecordID holds the string denoting the assigned_draw_record_id field in the database.
	FieldAssignedDrawRecordID = "assigned_draw_record_id"
	// FieldAssignedAt holds the string denoting the assigned_at field in the database.
	FieldAssignedAt = "assigned_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the lotteryprizepoolcode in the database.
	Table = "lottery_prize_pool_codes"
)

// Columns holds all SQL columns for lotteryprizepoolcode fields.
var Columns = []string{
	FieldID,
	FieldRedeemCodeID,
	FieldPrizeValue,
	FieldStatus,
	FieldAssignedToUserID,
	FieldAssignedDrawRecordID,
	FieldAssignedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the LotteryPrizePoolCode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRedeemCodeID orders the results by the redeem_code_id field.
func ByRedeemCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemCodeID, opts...).ToFunc()
}

// ByPrizeValue orders the results by the prize_value field.
func ByPrizeValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeValue, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAssignedToUserID orders the results by the assigned_to_user_id field.
func ByAssignedToUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignedToUserID, opts...).ToFunc()
}

// ByAssignedDrawRecordID orders the results by the assigned_draw_record_id field.
func ByAssignedDrawRecordID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignedDrawRecordID, opts...).ToFunc()
}

// ByAssignedAt orders the results by the assigned_at field.
func ByAssignedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
