// Code generated by ent, DO NOT EDIT.

package lotteryprizepoolcode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldLTE(FieldID, id))
}

// RedeemCodeID applies equality check predicate on the "redeem_code_id" field. It's identical to RedeemCodeIDEQ.
func RedeemCodeID(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEQ(FieldRedeemCodeID, v))
}

// PrizeValue applies equality check predicate on the "prize_value" field. It's identical to PrizeValueEQ.
func PrizeValue(v float64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEQ(FieldPrizeValue, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEQ(FieldStatus, v))
}

// AssignedToUserID applies equality check predicate on the "assigned_to_user_id" field. It's identical to AssignedToUserIDEQ.
func AssignedToUserID(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEQ(FieldAssignedToUserID, v))
}

// AssignedDrawRecordID applies equality check predicate on the "assigned_draw_record_id" field. It's identical to AssignedDrawRecordIDEQ.
func AssignedDrawRecordID(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEQ(FieldAssignedDrawRecordID, v))
}

// AssignedAt applies equality check predicate on the "assigned_at" field. It's identical to AssignedAtEQ.
func AssignedAt(v time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEQ(FieldAssignedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEQ(FieldCreatedAt, v))
}

// RedeemCodeIDEQ applies the EQ predicate on the "redeem_code_id" field.
func RedeemCodeIDEQ(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDNEQ applies the NEQ predicate on the "redeem_code_id" field.
func RedeemCodeIDNEQ(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDIn applies the In predicate on the "redeem_code_id" field.
func RedeemCodeIDIn(vs ...int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDNotIn applies the NotIn predicate on the "redeem_code_id" field.
func RedeemCodeIDNotIn(vs ...int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNotIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDGT applies the GT predicate on the "redeem_code_id" field.
func RedeemCodeIDGT(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldGT(FieldRedeemCodeID, v))
}

// RedeemCodeIDGTE applies the GTE predicate on the "redeem_code_id" field.
func RedeemCodeIDGTE(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldGTE(FieldRedeemCodeID, v))
}

// RedeemCodeIDLT applies the LT predicate on the "redeem_code_id" field.
func RedeemCodeIDLT(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldLT(FieldRedeemCodeID, v))
}

// RedeemCodeIDLTE applies the LTE predicate on the "redeem_code_id" field.
func RedeemCodeIDLTE(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldLTE(FieldRedeemCodeID, v))
}

// PrizeValueEQ applies the EQ predicate on the "prize_value" field.
func PrizeValueEQ(v float64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEQ(FieldPrizeValue, v))
}

// PrizeValueNEQ applies the NEQ predicate on the "prize_value" field.
func PrizeValueNEQ(v float64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNEQ(FieldPrizeValue, v))
}

// PrizeValueIn applies the In predicate on the "prize_value" field.
func PrizeValueIn(vs ...float64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldIn(FieldPrizeValue, vs...))
}

// PrizeValueNotIn applies the NotIn predicate on the "prize_value" field.
func PrizeValueNotIn(vs ...float64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNotIn(FieldPrizeValue, vs...))
}

// PrizeValueGT applies the GT predicate on the "prize_value" field.
func PrizeValueGT(v float64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldGT(FieldPrizeValue, v))
}

// PrizeValueGTE applies the GTE predicate on the "prize_value" field.
func PrizeValueGTE(v float64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldGTE(FieldPrizeValue, v))
}

// PrizeValueLT applies the LT predicate on the "prize_value" field.
func PrizeValueLT(v float64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldLT(FieldPrizeValue, v))
}

// PrizeValueLTE applies the LTE predicate on the "prize_value" field.
func PrizeValueLTE(v float64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldLTE(FieldPrizeValue, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldContainsFold(FieldStatus, v))
}

// AssignedToUserIDEQ applies the EQ predicate on the "assigned_to_user_id" field.
func AssignedToUserIDEQ(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEQ(FieldAssignedToUserID, v))
}

// AssignedToUserIDNEQ applies the NEQ predicate on the "assigned_to_user_id" field.
func AssignedToUserIDNEQ(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNEQ(FieldAssignedToUserID, v))
}

// AssignedToUserIDIn applies the In predicate on the "assigned_to_user_id" field.
func AssignedToUserIDIn(vs ...int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldIn(FieldAssignedToUserID, vs...))
}

// AssignedToUserIDNotIn applies the NotIn predicate on the "assigned_to_user_id" field.
func AssignedToUserIDNotIn(vs ...int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNotIn(FieldAssignedToUserID, vs...))
}

// AssignedToUserIDGT applies the GT predicate on the "assigned_to_user_id" field.
func AssignedToUserIDGT(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldGT(FieldAssignedToUserID, v))
}

// AssignedToUserIDGTE applies the GTE predicate on the "assigned_to_user_id" field.
func AssignedToUserIDGTE(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldGTE(FieldAssignedToUserID, v))
}

// AssignedToUserIDLT applies the LT predicate on the "assigned_to_user_id" field.
func AssignedToUserIDLT(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldLT(FieldAssignedToUserID, v))
}

// AssignedToUserIDLTE applies the LTE predicate on the "assigned_to_user_id" field.
func AssignedToUserIDLTE(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldLTE(FieldAssignedToUserID, v))
}

// AssignedToUserIDIsNil applies the IsNil predicate on the "assigned_to_user_id" field.
func AssignedToUserIDIsNil() predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldIsNull(FieldAssignedToUserID))
}

// AssignedToUserIDNotNil applies the NotNil predicate on the "assigned_to_user_id" field.
func AssignedToUserIDNotNil() predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNotNull(FieldAssignedToUserID))
}

// AssignedDrawRecordIDEQ applies the EQ predicate on the "assigned_draw_record_id" field.
func AssignedDrawRecordIDEQ(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEQ(FieldAssignedDrawRecordID, v))
}

// AssignedDrawRecordIDNEQ applies the NEQ predicate on the "assigned_draw_record_id" field.
func AssignedDrawRecordIDNEQ(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNEQ(FieldAssignedDrawRecordID, v))
}

// AssignedDrawRecordIDIn applies the In predicate on the "assigned_draw_record_id" field.
func AssignedDrawRecordIDIn(vs ...int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldIn(FieldAssignedDrawRecordID, vs...))
}

// AssignedDrawRecordIDNotIn applies the NotIn predicate on the "assigned_draw_record_id" field.
func AssignedDrawRecordIDNotIn(vs ...int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNotIn(FieldAssignedDrawRecordID, vs...))
}

// AssignedDrawRecordIDGT applies the GT predicate on the "assigned_draw_record_id" field.
func AssignedDrawRecordIDGT(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldGT(FieldAssignedDrawRecordID, v))
}

// AssignedDrawRecordIDGTE applies the GTE predicate on the "assigned_draw_record_id" field.
func AssignedDrawRecordIDGTE(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldGTE(FieldAssignedDrawRecordID, v))
}

// AssignedDrawRecordIDLT applies the LT predicate on the "assigned_draw_record_id" field.
func AssignedDrawRecordIDLT(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldLT(FieldAssignedDrawRecordID, v))
}

// AssignedDrawRecordIDLTE applies the LTE predicate on the "assigned_draw_record_id" field.
func AssignedDrawRecordIDLTE(v int64) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldLTE(FieldAssignedDrawRecordID, v))
}

// AssignedDrawRecordIDIsNil applies the IsNil predicate on the "assigned_draw_record_id" field.
func AssignedDrawRecordIDIsNil() predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldIsNull(FieldAssignedDrawRecordID))
}

// AssignedDrawRecordIDNotNil applies the NotNil predicate on the "assigned_draw_record_id" field.
func AssignedDrawRecordIDNotNil() predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNotNull(FieldAssignedDrawRecordID))
}

// AssignedAtEQ applies the EQ predicate on the "assigned_at" field.
func AssignedAtEQ(v time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEQ(FieldAssignedAt, v))
}

// AssignedAtNEQ applies the NEQ predicate on the "assigned_at" field.
func AssignedAtNEQ(v time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNEQ(FieldAssignedAt, v))
}

// AssignedAtIn applies the In predicate on the "assigned_at" field.
func AssignedAtIn(vs ...time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldIn(FieldAssignedAt, vs...))
}

// AssignedAtNotIn applies the NotIn predicate on the "assigned_at" field.
func AssignedAtNotIn(vs ...time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNotIn(FieldAssignedAt, vs...))
}

// AssignedAtGT applies the GT predicate on the "assigned_at" field.
func AssignedAtGT(v time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldGT(FieldAssignedAt, v))
}

// AssignedAtGTE applies the GTE predicate on the "assigned_at" field.
func AssignedAtGTE(v time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldGTE(FieldAssignedAt, v))
}

// AssignedAtLT applies the LT predicate on the "assigned_at" field.
func AssignedAtLT(v time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldLT(FieldAssignedAt, v))
}

// AssignedAtLTE applies the LTE predicate on the "assigned_at" field.
func AssignedAtLTE(v time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldLTE(FieldAssignedAt, v))
}

// AssignedAtIsNil applies the IsNil predicate on the "assigned_at" field.
func AssignedAtIsNil() predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldIsNull(FieldAssignedAt))
}

// AssignedAtNotNil applies the NotNil predicate on the "assigned_at" field.
func AssignedAtNotNil() predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNotNull(FieldAssignedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LotteryPrizePoolCode) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LotteryPrizePoolCode) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LotteryPrizePoolCode) predicate.LotteryPrizePoolCode {
	return predicate.LotteryPrizePoolCode(sql.NotPredicates(p))
}
