// Code generated by ent, DO NOT EDIT.

package lotterydrawrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the lotterydrawrecord type in the database.
	Label = "lottery_draw_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPrizeName holds the string denoting the prize_name field in the database.
	FieldPrizeName = "prize_name"
	// FieldPrizeValue holds the string denoting the prize_value field in the database.
	FieldPrizeValue = "prize_value"
	// FieldPrizePoolCodeID holds the string denoting the prize_pool_code_id field in the database.
	FieldPrizePoolCodeID = "prize_pool_code_id"
	// FieldPrizeRedeemCodeID holds the string denoting the prize_redeem_code_id field in the database.
	FieldPrizeRedeemCodeID = "prize_redeem_code_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the lotterydrawrecord in the database.
	Table = "lottery_draw_records"
)

// Columns holds all SQL columns for lotterydrawrecord fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldPrizeName,
	FieldPrizeValue,
	FieldPrizePoolCodeID,
	FieldPrizeRedeemCodeID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the LotteryDrawRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPrizeName orders the results by the prize_name field.
func ByPrizeName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeName, opts...).ToFunc()
}

// ByPrizeValue orders the results by the prize_value field.
func ByPrizeValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeValue, opts...).ToFunc()
}

// ByPrizePoolCodeID orders the results by the prize_pool_code_id field.
func ByPrizePoolCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizePoolCodeID, opts...).ToFunc()
}

// ByPrizeRedeemCodeID orders the results by the prize_redeem_code_id field.
func ByPrizeRedeemCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrizeRedeemCodeID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
