// Code generated by ent, DO NOT EDIT.

package lotterydrawrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldEQ(FieldUserID, v))
}

// PrizeName applies equality check predicate on the "prize_name" field. It's identical to PrizeNameEQ.
func PrizeName(v string) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldEQ(FieldPrizeName, v))
}

// PrizeValue applies equality check predicate on the "prize_value" field. It's identical to PrizeValueEQ.
func PrizeValue(v float64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldEQ(FieldPrizeValue, v))
}

// PrizePoolCodeID applies equality check predicate on the "prize_pool_code_id" field. It's identical to PrizePoolCodeIDEQ.
func PrizePoolCodeID(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldEQ(FieldPrizePoolCodeID, v))
}

// PrizeRedeemCodeID applies equality check predicate on the "prize_redeem_code_id" field. It's identical to PrizeRedeemCodeIDEQ.
func PrizeRedeemCodeID(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldEQ(FieldPrizeRedeemCodeID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldLTE(FieldUserID, v))
}

// PrizeNameEQ applies the EQ predicate on the "prize_name" field.
func PrizeNameEQ(v string) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldEQ(FieldPrizeName, v))
}

// PrizeNameNEQ applies the NEQ predicate on the "prize_name" field.
func PrizeNameNEQ(v string) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldNEQ(FieldPrizeName, v))
}

// PrizeNameIn applies the In predicate on the "prize_name" field.
func PrizeNameIn(vs ...string) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldIn(FieldPrizeName, vs...))
}

// PrizeNameNotIn applies the NotIn predicate on the "prize_name" field.
func PrizeNameNotIn(vs ...string) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldNotIn(FieldPrizeName, vs...))
}

// PrizeNameGT applies the GT predicate on the "prize_name" field.
func PrizeNameGT(v string) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldGT(FieldPrizeName, v))
}

// PrizeNameGTE applies the GTE predicate on the "prize_name" field.
func PrizeNameGTE(v string) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldGTE(FieldPrizeName, v))
}

// PrizeNameLT applies the LT predicate on the "prize_name" field.
func PrizeNameLT(v string) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldLT(FieldPrizeName, v))
}

// PrizeNameLTE applies the LTE predicate on the "prize_name" field.
func PrizeNameLTE(v string) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldLTE(FieldPrizeName, v))
}

// PrizeNameContains applies the Contains predicate on the "prize_name" field.
func PrizeNameContains(v string) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldContains(FieldPrizeName, v))
}

// PrizeNameHasPrefix applies the HasPrefix predicate on the "prize_name" field.
func PrizeNameHasPrefix(v string) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldHasPrefix(FieldPrizeName, v))
}

// PrizeNameHasSuffix applies the HasSuffix predicate on the "prize_name" field.
func PrizeNameHasSuffix(v string) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldHasSuffix(FieldPrizeName, v))
}

// PrizeNameEqualFold applies the EqualFold predicate on the "prize_name" field.
func PrizeNameEqualFold(v string) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldEqualFold(FieldPrizeName, v))
}

// PrizeNameContainsFold applies the ContainsFold predicate on the "prize_name" field.
func PrizeNameContainsFold(v string) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldContainsFold(FieldPrizeName, v))
}

// PrizeValueEQ applies the EQ predicate on the "prize_value" field.
func PrizeValueEQ(v float64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldEQ(FieldPrizeValue, v))
}

// PrizeValueNEQ applies the NEQ predicate on the "prize_value" field.
func PrizeValueNEQ(v float64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldNEQ(FieldPrizeValue, v))
}

// PrizeValueIn applies the In predicate on the "prize_value" field.
func PrizeValueIn(vs ...float64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldIn(FieldPrizeValue, vs...))
}

// PrizeValueNotIn applies the NotIn predicate on the "prize_value" field.
func PrizeValueNotIn(vs ...float64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldNotIn(FieldPrizeValue, vs...))
}

// PrizeValueGT applies the GT predicate on the "prize_value" field.
func PrizeValueGT(v float64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldGT(FieldPrizeValue, v))
}

// PrizeValueGTE applies the GTE predicate on the "prize_value" field.
func PrizeValueGTE(v float64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldGTE(FieldPrizeValue, v))
}

// PrizeValueLT applies the LT predicate on the "prize_value" field.
func PrizeValueLT(v float64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldLT(FieldPrizeValue, v))
}

// PrizeValueLTE applies the LTE predicate on the "prize_value" field.
func PrizeValueLTE(v float64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldLTE(FieldPrizeValue, v))
}

// PrizePoolCodeIDEQ applies the EQ predicate on the "prize_pool_code_id" field.
func PrizePoolCodeIDEQ(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldEQ(FieldPrizePoolCodeID, v))
}

// PrizePoolCodeIDNEQ applies the NEQ predicate on the "prize_pool_code_id" field.
func PrizePoolCodeIDNEQ(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldNEQ(FieldPrizePoolCodeID, v))
}

// PrizePoolCodeIDIn applies the In predicate on the "prize_pool_code_id" field.
func PrizePoolCodeIDIn(vs ...int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldIn(FieldPrizePoolCodeID, vs...))
}

// PrizePoolCodeIDNotIn applies the NotIn predicate on the "prize_pool_code_id" field.
func PrizePoolCodeIDNotIn(vs ...int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldNotIn(FieldPrizePoolCodeID, vs...))
}

// PrizePoolCodeIDGT applies the GT predicate on the "prize_pool_code_id" field.
func PrizePoolCodeIDGT(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldGT(FieldPrizePoolCodeID, v))
}

// PrizePoolCodeIDGTE applies the GTE predicate on the "prize_pool_code_id" field.
func PrizePoolCodeIDGTE(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldGTE(FieldPrizePoolCodeID, v))
}

// PrizePoolCodeIDLT applies the LT predicate on the "prize_pool_code_id" field.
func PrizePoolCodeIDLT(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldLT(FieldPrizePoolCodeID, v))
}

// PrizePoolCodeIDLTE applies the LTE predicate on the "prize_pool_code_id" field.
func PrizePoolCodeIDLTE(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldLTE(FieldPrizePoolCodeID, v))
}

// PrizeRedeemCodeIDEQ applies the EQ predicate on the "prize_redeem_code_id" field.
func PrizeRedeemCodeIDEQ(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldEQ(FieldPrizeRedeemCodeID, v))
}

// PrizeRedeemCodeIDNEQ applies the NEQ predicate on the "prize_redeem_code_id" field.
func PrizeRedeemCodeIDNEQ(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldNEQ(FieldPrizeRedeemCodeID, v))
}

// PrizeRedeemCodeIDIn applies the In predicate on the "prize_redeem_code_id" field.
func PrizeRedeemCodeIDIn(vs ...int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldIn(FieldPrizeRedeemCodeID, vs...))
}

// PrizeRedeemCodeIDNotIn applies the NotIn predicate on the "prize_redeem_code_id" field.
func PrizeRedeemCodeIDNotIn(vs ...int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldNotIn(FieldPrizeRedeemCodeID, vs...))
}

// PrizeRedeemCodeIDGT applies the GT predicate on the "prize_redeem_code_id" field.
func PrizeRedeemCodeIDGT(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldGT(FieldPrizeRedeemCodeID, v))
}

// PrizeRedeemCodeIDGTE applies the GTE predicate on the "prize_redeem_code_id" field.
func PrizeRedeemCodeIDGTE(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldGTE(FieldPrizeRedeemCodeID, v))
}

// PrizeRedeemCodeIDLT applies the LT predicate on the "prize_redeem_code_id" field.
func PrizeRedeemCodeIDLT(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldLT(FieldPrizeRedeemCodeID, v))
}

// PrizeRedeemCodeIDLTE applies the LTE predicate on the "prize_redeem_code_id" field.
func PrizeRedeemCodeIDLTE(v int64) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldLTE(FieldPrizeRedeemCodeID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LotteryDrawRecord) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LotteryDrawRecord) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LotteryDrawRecord) predicate.LotteryDrawRecord {
	return predicate.LotteryDrawRecord(sql.NotPredicates(p))
}
