ALTER TABLE pp_video_tasks
    ADD COLUMN IF NOT EXISTS input_video_duration_milliseconds BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS output_width INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS output_height INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS frame_rate NUMERIC(12,4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS has_audio BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS kling_mode VARCHAR(32) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS billing_formula VARCHAR(32) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS billing_units NUMERIC(30,6) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS billing_unit_price NUMERIC(30,12) NOT NULL DEFAULT 0;
