// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/lotterydrawrecord"
)

// LotteryDrawRecord is the model entity for the LotteryDrawRecord schema.
type LotteryDrawRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// PrizeName holds the value of the "prize_name" field.
	PrizeName string `json:"prize_name,omitempty"`
	// PrizeValue holds the value of the "prize_value" field.
	PrizeValue float64 `json:"prize_value,omitempty"`
	// PrizePoolCodeID holds the value of the "prize_pool_code_id" field.
	PrizePoolCodeID int64 `json:"prize_pool_code_id,omitempty"`
	// PrizeRedeemCodeID holds the value of the "prize_redeem_code_id" field.
	PrizeRedeemCodeID int64 `json:"prize_redeem_code_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LotteryDrawRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lotterydrawrecord.FieldPrizeValue:
			values[i] = new(sql.NullFloat64)
		case lotterydrawrecord.FieldID, lotterydrawrecord.FieldUserID, lotterydrawrecord.FieldPrizePoolCodeID, lotterydrawrecord.FieldPrizeRedeemCodeID:
			values[i] = new(sql.NullInt64)
		case lotterydrawrecord.FieldPrizeName:
			values[i] = new(sql.NullString)
		case lotterydrawrecord.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LotteryDrawRecord fields.
func (_m *LotteryDrawRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lotterydrawrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case lotterydrawrecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case lotterydrawrecord.FieldPrizeName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prize_name", values[i])
			} else if value.Valid {
				_m.PrizeName = value.String
			}
		case lotterydrawrecord.FieldPrizeValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field prize_value", values[i])
			} else if value.Valid {
				_m.PrizeValue = value.Float64
			}
		case lotterydrawrecord.FieldPrizePoolCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prize_pool_code_id", values[i])
			} else if value.Valid {
				_m.PrizePoolCodeID = value.Int64
			}
		case lotterydrawrecord.FieldPrizeRedeemCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prize_redeem_code_id", values[i])
			} else if value.Valid {
				_m.PrizeRedeemCodeID = value.Int64
			}
		case lotterydrawrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LotteryDrawRecord.
// This includes values selected through modifiers, order, etc.
func (_m *LotteryDrawRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LotteryDrawRecord.
// Note that you need to call LotteryDrawRecord.Unwrap() before calling this method if this LotteryDrawRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LotteryDrawRecord) Update() *LotteryDrawRecordUpdateOne {
	return NewLotteryDrawRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LotteryDrawRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LotteryDrawRecord) Unwrap() *LotteryDrawRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LotteryDrawRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LotteryDrawRecord) String() string {
	var builder strings.Builder
	builder.WriteString("LotteryDrawRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("prize_name=")
	builder.WriteString(_m.PrizeName)
	builder.WriteString(", ")
	builder.WriteString("prize_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrizeValue))
	builder.WriteString(", ")
	builder.WriteString("prize_pool_code_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrizePoolCodeID))
	builder.WriteString(", ")
	builder.WriteString("prize_redeem_code_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrizeRedeemCodeID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LotteryDrawRecords is a parsable slice of LotteryDrawRecord.
type LotteryDrawRecords []*LotteryDrawRecord
