// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprizepoolcode"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryPrizePoolCodeDelete is the builder for deleting a LotteryPrizePoolCode entity.
type LotteryPrizePoolCodeDelete struct {
	config
	hooks    []Hook
	mutation *LotteryPrizePoolCodeMutation
}

// Where appends a list predicates to the LotteryPrizePoolCodeDelete builder.
func (_d *LotteryPrizePoolCodeDelete) Where(ps ...predicate.LotteryPrizePoolCode) *LotteryPrizePoolCodeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LotteryPrizePoolCodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LotteryPrizePoolCodeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LotteryPrizePoolCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(lotteryprizepoolcode.Table, sqlgraph.NewFieldSpec(lotteryprizepoolcode.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LotteryPrizePoolCodeDeleteOne is the builder for deleting a single LotteryPrizePoolCode entity.
type LotteryPrizePoolCodeDeleteOne struct {
	_d *LotteryPrizePoolCodeDelete
}

// Where appends a list predicates to the LotteryPrizePoolCodeDelete builder.
func (_d *LotteryPrizePoolCodeDeleteOne) Where(ps ...predicate.LotteryPrizePoolCode) *LotteryPrizePoolCodeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LotteryPrizePoolCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{lotteryprizepoolcode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LotteryPrizePoolCodeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
