// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/lotterychanceledger"
)

// LotteryChanceLedger is the model entity for the LotteryChanceLedger schema.
type LotteryChanceLedger struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Delta holds the value of the "delta" field.
	Delta int `json:"delta,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// SourceRedeemCodeID holds the value of the "source_redeem_code_id" field.
	SourceRedeemCodeID *int64 `json:"source_redeem_code_id,omitempty"`
	// DrawRecordID holds the value of the "draw_record_id" field.
	DrawRecordID *int64 `json:"draw_record_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LotteryChanceLedger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lotterychanceledger.FieldID, lotterychanceledger.FieldUserID, lotterychanceledger.FieldDelta, lotterychanceledger.FieldSourceRedeemCodeID, lotterychanceledger.FieldDrawRecordID:
			values[i] = new(sql.NullInt64)
		case lotterychanceledger.FieldReason:
			values[i] = new(sql.NullString)
		case lotterychanceledger.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LotteryChanceLedger fields.
func (_m *LotteryChanceLedger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lotterychanceledger.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case lotterychanceledger.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case lotterychanceledger.FieldDelta:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delta", values[i])
			} else if value.Valid {
				_m.Delta = int(value.Int64)
			}
		case lotterychanceledger.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case lotterychanceledger.FieldSourceRedeemCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_redeem_code_id", values[i])
			} else if value.Valid {
				_m.SourceRedeemCodeID = new(int64)
				*_m.SourceRedeemCodeID = value.Int64
			}
		case lotterychanceledger.FieldDrawRecordID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field draw_record_id", values[i])
			} else if value.Valid {
				_m.DrawRecordID = new(int64)
				*_m.DrawRecordID = value.Int64
			}
		case lotterychanceledger.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LotteryChanceLedger.
// This includes values selected through modifiers, order, etc.
func (_m *LotteryChanceLedger) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LotteryChanceLedger.
// Note that you need to call LotteryChanceLedger.Unwrap() before calling this method if this LotteryChanceLedger
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LotteryChanceLedger) Update() *LotteryChanceLedgerUpdateOne {
	return NewLotteryChanceLedgerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LotteryChanceLedger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LotteryChanceLedger) Unwrap() *LotteryChanceLedger {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LotteryChanceLedger is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LotteryChanceLedger) String() string {
	var builder strings.Builder
	builder.WriteString("LotteryChanceLedger(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("delta=")
	builder.WriteString(fmt.Sprintf("%v", _m.Delta))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	if v := _m.SourceRedeemCodeID; v != nil {
		builder.WriteString("source_redeem_code_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DrawRecordID; v != nil {
		builder.WriteString("draw_record_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LotteryChanceLedgers is a parsable slice of LotteryChanceLedger.
type LotteryChanceLedgers []*LotteryChanceLedger
