// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprizepoolcode"
)

// LotteryPrizePoolCode is the model entity for the LotteryPrizePoolCode schema.
type LotteryPrizePoolCode struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RedeemCodeID holds the value of the "redeem_code_id" field.
	RedeemCodeID int64 `json:"redeem_code_id,omitempty"`
	// PrizeValue holds the value of the "prize_value" field.
	PrizeValue float64 `json:"prize_value,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AssignedToUserID holds the value of the "assigned_to_user_id" field.
	AssignedToUserID *int64 `json:"assigned_to_user_id,omitempty"`
	// AssignedDrawRecordID holds the value of the "assigned_draw_record_id" field.
	AssignedDrawRecordID *int64 `json:"assigned_draw_record_id,omitempty"`
	// AssignedAt holds the value of the "assigned_at" field.
	AssignedAt *time.Time `json:"assigned_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LotteryPrizePoolCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lotteryprizepoolcode.FieldPrizeValue:
			values[i] = new(sql.NullFloat64)
		case lotteryprizepoolcode.FieldID, lotteryprizepoolcode.FieldRedeemCodeID, lotteryprizepoolcode.FieldAssignedToUserID, lotteryprizepoolcode.FieldAssignedDrawRecordID:
			values[i] = new(sql.NullInt64)
		case lotteryprizepoolcode.FieldStatus:
			values[i] = new(sql.NullString)
		case lotteryprizepoolcode.FieldAssignedAt, lotteryprizepoolcode.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LotteryPrizePoolCode fields.
func (_m *LotteryPrizePoolCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lotteryprizepoolcode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case lotteryprizepoolcode.FieldRedeemCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field redeem_code_id", values[i])
			} else if value.Valid {
				_m.RedeemCodeID = value.Int64
			}
		case lotteryprizepoolcode.FieldPrizeValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field prize_value", values[i])
			} else if value.Valid {
				_m.PrizeValue = value.Float64
			}
		case lotteryprizepoolcode.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case lotteryprizepoolcode.FieldAssignedToUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_to_user_id", values[i])
			} else if value.Valid {
				_m.AssignedToUserID = new(int64)
				*_m.AssignedToUserID = value.Int64
			}
		case lotteryprizepoolcode.FieldAssignedDrawRecordID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_draw_record_id", values[i])
			} else if value.Valid {
				_m.AssignedDrawRecordID = new(int64)
				*_m.AssignedDrawRecordID = value.Int64
			}
		case lotteryprizepoolcode.FieldAssignedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_at", values[i])
			} else if value.Valid {
				_m.AssignedAt = new(time.Time)
				*_m.AssignedAt = value.Time
			}
		case lotteryprizepoolcode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LotteryPrizePoolCode.
// This includes values selected through modifiers, order, etc.
func (_m *LotteryPrizePoolCode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LotteryPrizePoolCode.
// Note that you need to call LotteryPrizePoolCode.Unwrap() before calling this method if this LotteryPrizePoolCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LotteryPrizePoolCode) Update() *LotteryPrizePoolCodeUpdateOne {
	return NewLotteryPrizePoolCodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LotteryPrizePoolCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LotteryPrizePoolCode) Unwrap() *LotteryPrizePoolCode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LotteryPrizePoolCode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LotteryPrizePoolCode) String() string {
	var builder strings.Builder
	builder.WriteString("LotteryPrizePoolCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("redeem_code_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RedeemCodeID))
	builder.WriteString(", ")
	builder.WriteString("prize_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrizeValue))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.AssignedToUserID; v != nil {
		builder.WriteString("assigned_to_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AssignedDrawRecordID; v != nil {
		builder.WriteString("assigned_draw_record_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AssignedAt; v != nil {
		builder.WriteString("assigned_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LotteryPrizePoolCodes is a parsable slice of LotteryPrizePoolCode.
type LotteryPrizePoolCodes []*LotteryPrizePoolCode
