// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprizepoolcode"
)

// LotteryPrizePoolCodeCreate is the builder for creating a LotteryPrizePoolCode entity.
type LotteryPrizePoolCodeCreate struct {
	config
	mutation *LotteryPrizePoolCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_c *LotteryPrizePoolCodeCreate) SetRedeemCodeID(v int64) *LotteryPrizePoolCodeCreate {
	_c.mutation.SetRedeemCodeID(v)
	return _c
}

// SetPrizeValue sets the "prize_value" field.
func (_c *LotteryPrizePoolCodeCreate) SetPrizeValue(v float64) *LotteryPrizePoolCodeCreate {
	_c.mutation.SetPrizeValue(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *LotteryPrizePoolCodeCreate) SetStatus(v string) *LotteryPrizePoolCodeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LotteryPrizePoolCodeCreate) SetNillableStatus(v *string) *LotteryPrizePoolCodeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAssignedToUserID sets the "assigned_to_user_id" field.
func (_c *LotteryPrizePoolCodeCreate) SetAssignedToUserID(v int64) *LotteryPrizePoolCodeCreate {
	_c.mutation.SetAssignedToUserID(v)
	return _c
}

// SetNillableAssignedToUserID sets the "assigned_to_user_id" field if the given value is not nil.
func (_c *LotteryPrizePoolCodeCreate) SetNillableAssignedToUserID(v *int64) *LotteryPrizePoolCodeCreate {
	if v != nil {
		_c.SetAssignedToUserID(*v)
	}
	return _c
}

// SetAssignedDrawRecordID sets the "assigned_draw_record_id" field.
func (_c *LotteryPrizePoolCodeCreate) SetAssignedDrawRecordID(v int64) *LotteryPrizePoolCodeCreate {
	_c.mutation.SetAssignedDrawRecordID(v)
	return _c
}

// SetNillableAssignedDrawRecordID sets the "assigned_draw_record_id" field if the given value is not nil.
func (_c *LotteryPrizePoolCodeCreate) SetNillableAssignedDrawRecordID(v *int64) *LotteryPrizePoolCodeCreate {
	if v != nil {
		_c.SetAssignedDrawRecordID(*v)
	}
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *LotteryPrizePoolCodeCreate) SetAssignedAt(v time.Time) *LotteryPrizePoolCodeCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *LotteryPrizePoolCodeCreate) SetNillableAssignedAt(v *time.Time) *LotteryPrizePoolCodeCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryPrizePoolCodeCreate) SetCreatedAt(v time.Time) *LotteryPrizePoolCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryPrizePoolCodeCreate) SetNillableCreatedAt(v *time.Time) *LotteryPrizePoolCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the LotteryPrizePoolCodeMutation object of the builder.
func (_c *LotteryPrizePoolCodeCreate) Mutation() *LotteryPrizePoolCodeMutation {
	return _c.mutation
}

// Save creates the LotteryPrizePoolCode in the database.
func (_c *LotteryPrizePoolCodeCreate) Save(ctx context.Context) (*LotteryPrizePoolCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryPrizePoolCodeCreate) SaveX(ctx context.Context) *LotteryPrizePoolCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryPrizePoolCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryPrizePoolCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryPrizePoolCodeCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := lotteryprizepoolcode.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotteryprizepoolcode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryPrizePoolCodeCreate) check() error {
	if _, ok := _c.mutation.RedeemCodeID(); !ok {
		return &ValidationError{Name: "redeem_code_id", err: errors.New(`ent: missing required field "LotteryPrizePoolCode.redeem_code_id"`)}
	}
	if _, ok := _c.mutation.PrizeValue(); !ok {
		return &ValidationError{Name: "prize_value", err: errors.New(`ent: missing required field "LotteryPrizePoolCode.prize_value"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "LotteryPrizePoolCode.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryPrizePoolCode.created_at"`)}
	}
	return nil
}

func (_c *LotteryPrizePoolCodeCreate) sqlSave(ctx context.Context) (*LotteryPrizePoolCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryPrizePoolCodeCreate) createSpec() (*LotteryPrizePoolCode, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryPrizePoolCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotteryprizepoolcode.Table, sqlgraph.NewFieldSpec(lotteryprizepoolcode.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RedeemCodeID(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldRedeemCodeID, field.TypeInt64, value)
		_node.RedeemCodeID = value
	}
	if value, ok := _c.mutation.PrizeValue(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldPrizeValue, field.TypeFloat64, value)
		_node.PrizeValue = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AssignedToUserID(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldAssignedToUserID, field.TypeInt64, value)
		_node.AssignedToUserID = &value
	}
	if value, ok := _c.mutation.AssignedDrawRecordID(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldAssignedDrawRecordID, field.TypeInt64, value)
		_node.AssignedDrawRecordID = &value
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryPrizePoolCode.Create().
//		SetRedeemCodeID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryPrizePoolCodeUpsert) {
//			SetRedeemCodeID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryPrizePoolCodeCreate) OnConflict(opts ...sql.ConflictOption) *LotteryPrizePoolCodeUpsertOne {
	_c.conflict = opts
	return &LotteryPrizePoolCodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryPrizePoolCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryPrizePoolCodeCreate) OnConflictColumns(columns ...string) *LotteryPrizePoolCodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryPrizePoolCodeUpsertOne{
		create: _c,
	}
}

type (
	// LotteryPrizePoolCodeUpsertOne is the builder for "upsert"-ing
	//  one LotteryPrizePoolCode node.
	LotteryPrizePoolCodeUpsertOne struct {
		create *LotteryPrizePoolCodeCreate
	}

	// LotteryPrizePoolCodeUpsert is the "OnConflict" setter.
	LotteryPrizePoolCodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *LotteryPrizePoolCodeUpsert) SetRedeemCodeID(v int64) *LotteryPrizePoolCodeUpsert {
	u.Set(lotteryprizepoolcode.FieldRedeemCodeID, v)
	return u
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsert) UpdateRedeemCodeID() *LotteryPrizePoolCodeUpsert {
	u.SetExcluded(lotteryprizepoolcode.FieldRedeemCodeID)
	return u
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *LotteryPrizePoolCodeUpsert) AddRedeemCodeID(v int64) *LotteryPrizePoolCodeUpsert {
	u.Add(lotteryprizepoolcode.FieldRedeemCodeID, v)
	return u
}

// SetPrizeValue sets the "prize_value" field.
func (u *LotteryPrizePoolCodeUpsert) SetPrizeValue(v float64) *LotteryPrizePoolCodeUpsert {
	u.Set(lotteryprizepoolcode.FieldPrizeValue, v)
	return u
}

// UpdatePrizeValue sets the "prize_value" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsert) UpdatePrizeValue() *LotteryPrizePoolCodeUpsert {
	u.SetExcluded(lotteryprizepoolcode.FieldPrizeValue)
	return u
}

// AddPrizeValue adds v to the "prize_value" field.
func (u *LotteryPrizePoolCodeUpsert) AddPrizeValue(v float64) *LotteryPrizePoolCodeUpsert {
	u.Add(lotteryprizepoolcode.FieldPrizeValue, v)
	return u
}

// SetStatus sets the "status" field.
func (u *LotteryPrizePoolCodeUpsert) SetStatus(v string) *LotteryPrizePoolCodeUpsert {
	u.Set(lotteryprizepoolcode.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsert) UpdateStatus() *LotteryPrizePoolCodeUpsert {
	u.SetExcluded(lotteryprizepoolcode.FieldStatus)
	return u
}

// SetAssignedToUserID sets the "assigned_to_user_id" field.
func (u *LotteryPrizePoolCodeUpsert) SetAssignedToUserID(v int64) *LotteryPrizePoolCodeUpsert {
	u.Set(lotteryprizepoolcode.FieldAssignedToUserID, v)
	return u
}

// UpdateAssignedToUserID sets the "assigned_to_user_id" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsert) UpdateAssignedToUserID() *LotteryPrizePoolCodeUpsert {
	u.SetExcluded(lotteryprizepoolcode.FieldAssignedToUserID)
	return u
}

// AddAssignedToUserID adds v to the "assigned_to_user_id" field.
func (u *LotteryPrizePoolCodeUpsert) AddAssignedToUserID(v int64) *LotteryPrizePoolCodeUpsert {
	u.Add(lotteryprizepoolcode.FieldAssignedToUserID, v)
	return u
}

// ClearAssignedToUserID clears the value of the "assigned_to_user_id" field.
func (u *LotteryPrizePoolCodeUpsert) ClearAssignedToUserID() *LotteryPrizePoolCodeUpsert {
	u.SetNull(lotteryprizepoolcode.FieldAssignedToUserID)
	return u
}

// SetAssignedDrawRecordID sets the "assigned_draw_record_id" field.
func (u *LotteryPrizePoolCodeUpsert) SetAssignedDrawRecordID(v int64) *LotteryPrizePoolCodeUpsert {
	u.Set(lotteryprizepoolcode.FieldAssignedDrawRecordID, v)
	return u
}

// UpdateAssignedDrawRecordID sets the "assigned_draw_record_id" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsert) UpdateAssignedDrawRecordID() *LotteryPrizePoolCodeUpsert {
	u.SetExcluded(lotteryprizepoolcode.FieldAssignedDrawRecordID)
	return u
}

// AddAssignedDrawRecordID adds v to the "assigned_draw_record_id" field.
func (u *LotteryPrizePoolCodeUpsert) AddAssignedDrawRecordID(v int64) *LotteryPrizePoolCodeUpsert {
	u.Add(lotteryprizepoolcode.FieldAssignedDrawRecordID, v)
	return u
}

// ClearAssignedDrawRecordID clears the value of the "assigned_draw_record_id" field.
func (u *LotteryPrizePoolCodeUpsert) ClearAssignedDrawRecordID() *LotteryPrizePoolCodeUpsert {
	u.SetNull(lotteryprizepoolcode.FieldAssignedDrawRecordID)
	return u
}

// SetAssignedAt sets the "assigned_at" field.
func (u *LotteryPrizePoolCodeUpsert) SetAssignedAt(v time.Time) *LotteryPrizePoolCodeUpsert {
	u.Set(lotteryprizepoolcode.FieldAssignedAt, v)
	return u
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsert) UpdateAssignedAt() *LotteryPrizePoolCodeUpsert {
	u.SetExcluded(lotteryprizepoolcode.FieldAssignedAt)
	return u
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (u *LotteryPrizePoolCodeUpsert) ClearAssignedAt() *LotteryPrizePoolCodeUpsert {
	u.SetNull(lotteryprizepoolcode.FieldAssignedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryPrizePoolCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryPrizePoolCodeUpsertOne) UpdateNewValues() *LotteryPrizePoolCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotteryprizepoolcode.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryPrizePoolCode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryPrizePoolCodeUpsertOne) Ignore() *LotteryPrizePoolCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryPrizePoolCodeUpsertOne) DoNothing() *LotteryPrizePoolCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryPrizePoolCodeCreate.OnConflict
// documentation for more info.
func (u *LotteryPrizePoolCodeUpsertOne) Update(set func(*LotteryPrizePoolCodeUpsert)) *LotteryPrizePoolCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryPrizePoolCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *LotteryPrizePoolCodeUpsertOne) SetRedeemCodeID(v int64) *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *LotteryPrizePoolCodeUpsertOne) AddRedeemCodeID(v int64) *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.AddRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsertOne) UpdateRedeemCodeID() *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// SetPrizeValue sets the "prize_value" field.
func (u *LotteryPrizePoolCodeUpsertOne) SetPrizeValue(v float64) *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.SetPrizeValue(v)
	})
}

// AddPrizeValue adds v to the "prize_value" field.
func (u *LotteryPrizePoolCodeUpsertOne) AddPrizeValue(v float64) *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.AddPrizeValue(v)
	})
}

// UpdatePrizeValue sets the "prize_value" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsertOne) UpdatePrizeValue() *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.UpdatePrizeValue()
	})
}

// SetStatus sets the "status" field.
func (u *LotteryPrizePoolCodeUpsertOne) SetStatus(v string) *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsertOne) UpdateStatus() *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.UpdateStatus()
	})
}

// SetAssignedToUserID sets the "assigned_to_user_id" field.
func (u *LotteryPrizePoolCodeUpsertOne) SetAssignedToUserID(v int64) *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.SetAssignedToUserID(v)
	})
}

// AddAssignedToUserID adds v to the "assigned_to_user_id" field.
func (u *LotteryPrizePoolCodeUpsertOne) AddAssignedToUserID(v int64) *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.AddAssignedToUserID(v)
	})
}

// UpdateAssignedToUserID sets the "assigned_to_user_id" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsertOne) UpdateAssignedToUserID() *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.UpdateAssignedToUserID()
	})
}

// ClearAssignedToUserID clears the value of the "assigned_to_user_id" field.
func (u *LotteryPrizePoolCodeUpsertOne) ClearAssignedToUserID() *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.ClearAssignedToUserID()
	})
}

// SetAssignedDrawRecordID sets the "assigned_draw_record_id" field.
func (u *LotteryPrizePoolCodeUpsertOne) SetAssignedDrawRecordID(v int64) *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.SetAssignedDrawRecordID(v)
	})
}

// AddAssignedDrawRecordID adds v to the "assigned_draw_record_id" field.
func (u *LotteryPrizePoolCodeUpsertOne) AddAssignedDrawRecordID(v int64) *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.AddAssignedDrawRecordID(v)
	})
}

// UpdateAssignedDrawRecordID sets the "assigned_draw_record_id" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsertOne) UpdateAssignedDrawRecordID() *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.UpdateAssignedDrawRecordID()
	})
}

// ClearAssignedDrawRecordID clears the value of the "assigned_draw_record_id" field.
func (u *LotteryPrizePoolCodeUpsertOne) ClearAssignedDrawRecordID() *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.ClearAssignedDrawRecordID()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *LotteryPrizePoolCodeUpsertOne) SetAssignedAt(v time.Time) *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsertOne) UpdateAssignedAt() *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.UpdateAssignedAt()
	})
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (u *LotteryPrizePoolCodeUpsertOne) ClearAssignedAt() *LotteryPrizePoolCodeUpsertOne {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.ClearAssignedAt()
	})
}

// Exec executes the query.
func (u *LotteryPrizePoolCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryPrizePoolCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryPrizePoolCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryPrizePoolCodeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryPrizePoolCodeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryPrizePoolCodeCreateBulk is the builder for creating many LotteryPrizePoolCode entities in bulk.
type LotteryPrizePoolCodeCreateBulk struct {
	config
	err      error
	builders []*LotteryPrizePoolCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryPrizePoolCode entities in the database.
func (_c *LotteryPrizePoolCodeCreateBulk) Save(ctx context.Context) ([]*LotteryPrizePoolCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryPrizePoolCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryPrizePoolCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryPrizePoolCodeCreateBulk) SaveX(ctx context.Context) []*LotteryPrizePoolCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryPrizePoolCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryPrizePoolCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryPrizePoolCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryPrizePoolCodeUpsert) {
//			SetRedeemCodeID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryPrizePoolCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryPrizePoolCodeUpsertBulk {
	_c.conflict = opts
	return &LotteryPrizePoolCodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryPrizePoolCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryPrizePoolCodeCreateBulk) OnConflictColumns(columns ...string) *LotteryPrizePoolCodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryPrizePoolCodeUpsertBulk{
		create: _c,
	}
}

// LotteryPrizePoolCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryPrizePoolCode nodes.
type LotteryPrizePoolCodeUpsertBulk struct {
	create *LotteryPrizePoolCodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryPrizePoolCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryPrizePoolCodeUpsertBulk) UpdateNewValues() *LotteryPrizePoolCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotteryprizepoolcode.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryPrizePoolCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryPrizePoolCodeUpsertBulk) Ignore() *LotteryPrizePoolCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryPrizePoolCodeUpsertBulk) DoNothing() *LotteryPrizePoolCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryPrizePoolCodeCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryPrizePoolCodeUpsertBulk) Update(set func(*LotteryPrizePoolCodeUpsert)) *LotteryPrizePoolCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryPrizePoolCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *LotteryPrizePoolCodeUpsertBulk) SetRedeemCodeID(v int64) *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *LotteryPrizePoolCodeUpsertBulk) AddRedeemCodeID(v int64) *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.AddRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsertBulk) UpdateRedeemCodeID() *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// SetPrizeValue sets the "prize_value" field.
func (u *LotteryPrizePoolCodeUpsertBulk) SetPrizeValue(v float64) *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.SetPrizeValue(v)
	})
}

// AddPrizeValue adds v to the "prize_value" field.
func (u *LotteryPrizePoolCodeUpsertBulk) AddPrizeValue(v float64) *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.AddPrizeValue(v)
	})
}

// UpdatePrizeValue sets the "prize_value" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsertBulk) UpdatePrizeValue() *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.UpdatePrizeValue()
	})
}

// SetStatus sets the "status" field.
func (u *LotteryPrizePoolCodeUpsertBulk) SetStatus(v string) *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsertBulk) UpdateStatus() *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.UpdateStatus()
	})
}

// SetAssignedToUserID sets the "assigned_to_user_id" field.
func (u *LotteryPrizePoolCodeUpsertBulk) SetAssignedToUserID(v int64) *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.SetAssignedToUserID(v)
	})
}

// AddAssignedToUserID adds v to the "assigned_to_user_id" field.
func (u *LotteryPrizePoolCodeUpsertBulk) AddAssignedToUserID(v int64) *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.AddAssignedToUserID(v)
	})
}

// UpdateAssignedToUserID sets the "assigned_to_user_id" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsertBulk) UpdateAssignedToUserID() *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.UpdateAssignedToUserID()
	})
}

// ClearAssignedToUserID clears the value of the "assigned_to_user_id" field.
func (u *LotteryPrizePoolCodeUpsertBulk) ClearAssignedToUserID() *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.ClearAssignedToUserID()
	})
}

// SetAssignedDrawRecordID sets the "assigned_draw_record_id" field.
func (u *LotteryPrizePoolCodeUpsertBulk) SetAssignedDrawRecordID(v int64) *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.SetAssignedDrawRecordID(v)
	})
}

// AddAssignedDrawRecordID adds v to the "assigned_draw_record_id" field.
func (u *LotteryPrizePoolCodeUpsertBulk) AddAssignedDrawRecordID(v int64) *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.AddAssignedDrawRecordID(v)
	})
}

// UpdateAssignedDrawRecordID sets the "assigned_draw_record_id" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsertBulk) UpdateAssignedDrawRecordID() *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.UpdateAssignedDrawRecordID()
	})
}

// ClearAssignedDrawRecordID clears the value of the "assigned_draw_record_id" field.
func (u *LotteryPrizePoolCodeUpsertBulk) ClearAssignedDrawRecordID() *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.ClearAssignedDrawRecordID()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *LotteryPrizePoolCodeUpsertBulk) SetAssignedAt(v time.Time) *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *LotteryPrizePoolCodeUpsertBulk) UpdateAssignedAt() *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.UpdateAssignedAt()
	})
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (u *LotteryPrizePoolCodeUpsertBulk) ClearAssignedAt() *LotteryPrizePoolCodeUpsertBulk {
	return u.Update(func(s *LotteryPrizePoolCodeUpsert) {
		s.ClearAssignedAt()
	})
}

// Exec executes the query.
func (u *LotteryPrizePoolCodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryPrizePoolCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryPrizePoolCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryPrizePoolCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
