// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterychanceledger"
)

// LotteryChanceLedgerCreate is the builder for creating a LotteryChanceLedger entity.
type LotteryChanceLedgerCreate struct {
	config
	mutation *LotteryChanceLedgerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *LotteryChanceLedgerCreate) SetUserID(v int64) *LotteryChanceLedgerCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetDelta sets the "delta" field.
func (_c *LotteryChanceLedgerCreate) SetDelta(v int) *LotteryChanceLedgerCreate {
	_c.mutation.SetDelta(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *LotteryChanceLedgerCreate) SetReason(v string) *LotteryChanceLedgerCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetSourceRedeemCodeID sets the "source_redeem_code_id" field.
func (_c *LotteryChanceLedgerCreate) SetSourceRedeemCodeID(v int64) *LotteryChanceLedgerCreate {
	_c.mutation.SetSourceRedeemCodeID(v)
	return _c
}

// SetNillableSourceRedeemCodeID sets the "source_redeem_code_id" field if the given value is not nil.
func (_c *LotteryChanceLedgerCreate) SetNillableSourceRedeemCodeID(v *int64) *LotteryChanceLedgerCreate {
	if v != nil {
		_c.SetSourceRedeemCodeID(*v)
	}
	return _c
}

// SetDrawRecordID sets the "draw_record_id" field.
func (_c *LotteryChanceLedgerCreate) SetDrawRecordID(v int64) *LotteryChanceLedgerCreate {
	_c.mutation.SetDrawRecordID(v)
	return _c
}

// SetNillableDrawRecordID sets the "draw_record_id" field if the given value is not nil.
func (_c *LotteryChanceLedgerCreate) SetNillableDrawRecordID(v *int64) *LotteryChanceLedgerCreate {
	if v != nil {
		_c.SetDrawRecordID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryChanceLedgerCreate) SetCreatedAt(v time.Time) *LotteryChanceLedgerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryChanceLedgerCreate) SetNillableCreatedAt(v *time.Time) *LotteryChanceLedgerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the LotteryChanceLedgerMutation object of the builder.
func (_c *LotteryChanceLedgerCreate) Mutation() *LotteryChanceLedgerMutation {
	return _c.mutation
}

// Save creates the LotteryChanceLedger in the database.
func (_c *LotteryChanceLedgerCreate) Save(ctx context.Context) (*LotteryChanceLedger, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryChanceLedgerCreate) SaveX(ctx context.Context) *LotteryChanceLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryChanceLedgerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryChanceLedgerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryChanceLedgerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotterychanceledger.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryChanceLedgerCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "LotteryChanceLedger.user_id"`)}
	}
	if _, ok := _c.mutation.Delta(); !ok {
		return &ValidationError{Name: "delta", err: errors.New(`ent: missing required field "LotteryChanceLedger.delta"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "LotteryChanceLedger.reason"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryChanceLedger.created_at"`)}
	}
	return nil
}

func (_c *LotteryChanceLedgerCreate) sqlSave(ctx context.Context) (*LotteryChanceLedger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryChanceLedgerCreate) createSpec() (*LotteryChanceLedger, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryChanceLedger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotterychanceledger.Table, sqlgraph.NewFieldSpec(lotterychanceledger.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(lotterychanceledger.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Delta(); ok {
		_spec.SetField(lotterychanceledger.FieldDelta, field.TypeInt, value)
		_node.Delta = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(lotterychanceledger.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.SourceRedeemCodeID(); ok {
		_spec.SetField(lotterychanceledger.FieldSourceRedeemCodeID, field.TypeInt64, value)
		_node.SourceRedeemCodeID = &value
	}
	if value, ok := _c.mutation.DrawRecordID(); ok {
		_spec.SetField(lotterychanceledger.FieldDrawRecordID, field.TypeInt64, value)
		_node.DrawRecordID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotterychanceledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryChanceLedger.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryChanceLedgerUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryChanceLedgerCreate) OnConflict(opts ...sql.ConflictOption) *LotteryChanceLedgerUpsertOne {
	_c.conflict = opts
	return &LotteryChanceLedgerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryChanceLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryChanceLedgerCreate) OnConflictColumns(columns ...string) *LotteryChanceLedgerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryChanceLedgerUpsertOne{
		create: _c,
	}
}

type (
	// LotteryChanceLedgerUpsertOne is the builder for "upsert"-ing
	//  one LotteryChanceLedger node.
	LotteryChanceLedgerUpsertOne struct {
		create *LotteryChanceLedgerCreate
	}

	// LotteryChanceLedgerUpsert is the "OnConflict" setter.
	LotteryChanceLedgerUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *LotteryChanceLedgerUpsert) SetUserID(v int64) *LotteryChanceLedgerUpsert {
	u.Set(lotterychanceledger.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryChanceLedgerUpsert) UpdateUserID() *LotteryChanceLedgerUpsert {
	u.SetExcluded(lotterychanceledger.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryChanceLedgerUpsert) AddUserID(v int64) *LotteryChanceLedgerUpsert {
	u.Add(lotterychanceledger.FieldUserID, v)
	return u
}

// SetDelta sets the "delta" field.
func (u *LotteryChanceLedgerUpsert) SetDelta(v int) *LotteryChanceLedgerUpsert {
	u.Set(lotterychanceledger.FieldDelta, v)
	return u
}

// UpdateDelta sets the "delta" field to the value that was provided on create.
func (u *LotteryChanceLedgerUpsert) UpdateDelta() *LotteryChanceLedgerUpsert {
	u.SetExcluded(lotterychanceledger.FieldDelta)
	return u
}

// AddDelta adds v to the "delta" field.
func (u *LotteryChanceLedgerUpsert) AddDelta(v int) *LotteryChanceLedgerUpsert {
	u.Add(lotterychanceledger.FieldDelta, v)
	return u
}

// SetReason sets the "reason" field.
func (u *LotteryChanceLedgerUpsert) SetReason(v string) *LotteryChanceLedgerUpsert {
	u.Set(lotterychanceledger.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *LotteryChanceLedgerUpsert) UpdateReason() *LotteryChanceLedgerUpsert {
	u.SetExcluded(lotterychanceledger.FieldReason)
	return u
}

// SetSourceRedeemCodeID sets the "source_redeem_code_id" field.
func (u *LotteryChanceLedgerUpsert) SetSourceRedeemCodeID(v int64) *LotteryChanceLedgerUpsert {
	u.Set(lotterychanceledger.FieldSourceRedeemCodeID, v)
	return u
}

// UpdateSourceRedeemCodeID sets the "source_redeem_code_id" field to the value that was provided on create.
func (u *LotteryChanceLedgerUpsert) UpdateSourceRedeemCodeID() *LotteryChanceLedgerUpsert {
	u.SetExcluded(lotterychanceledger.FieldSourceRedeemCodeID)
	return u
}

// AddSourceRedeemCodeID adds v to the "source_redeem_code_id" field.
func (u *LotteryChanceLedgerUpsert) AddSourceRedeemCodeID(v int64) *LotteryChanceLedgerUpsert {
	u.Add(lotterychanceledger.FieldSourceRedeemCodeID, v)
	return u
}

// ClearSourceRedeemCodeID clears the value of the "source_redeem_code_id" field.
func (u *LotteryChanceLedgerUpsert) ClearSourceRedeemCodeID() *LotteryChanceLedgerUpsert {
	u.SetNull(lotterychanceledger.FieldSourceRedeemCodeID)
	return u
}

// SetDrawRecordID sets the "draw_record_id" field.
func (u *LotteryChanceLedgerUpsert) SetDrawRecordID(v int64) *LotteryChanceLedgerUpsert {
	u.Set(lotterychanceledger.FieldDrawRecordID, v)
	return u
}

// UpdateDrawRecordID sets the "draw_record_id" field to the value that was provided on create.
func (u *LotteryChanceLedgerUpsert) UpdateDrawRecordID() *LotteryChanceLedgerUpsert {
	u.SetExcluded(lotterychanceledger.FieldDrawRecordID)
	return u
}

// AddDrawRecordID adds v to the "draw_record_id" field.
func (u *LotteryChanceLedgerUpsert) AddDrawRecordID(v int64) *LotteryChanceLedgerUpsert {
	u.Add(lotterychanceledger.FieldDrawRecordID, v)
	return u
}

// ClearDrawRecordID clears the value of the "draw_record_id" field.
func (u *LotteryChanceLedgerUpsert) ClearDrawRecordID() *LotteryChanceLedgerUpsert {
	u.SetNull(lotterychanceledger.FieldDrawRecordID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryChanceLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryChanceLedgerUpsertOne) UpdateNewValues() *LotteryChanceLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotterychanceledger.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryChanceLedger.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryChanceLedgerUpsertOne) Ignore() *LotteryChanceLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryChanceLedgerUpsertOne) DoNothing() *LotteryChanceLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryChanceLedgerCreate.OnConflict
// documentation for more info.
func (u *LotteryChanceLedgerUpsertOne) Update(set func(*LotteryChanceLedgerUpsert)) *LotteryChanceLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryChanceLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *LotteryChanceLedgerUpsertOne) SetUserID(v int64) *LotteryChanceLedgerUpsertOne {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryChanceLedgerUpsertOne) AddUserID(v int64) *LotteryChanceLedgerUpsertOne {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryChanceLedgerUpsertOne) UpdateUserID() *LotteryChanceLedgerUpsertOne {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.UpdateUserID()
	})
}

// SetDelta sets the "delta" field.
func (u *LotteryChanceLedgerUpsertOne) SetDelta(v int) *LotteryChanceLedgerUpsertOne {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.SetDelta(v)
	})
}

// AddDelta adds v to the "delta" field.
func (u *LotteryChanceLedgerUpsertOne) AddDelta(v int) *LotteryChanceLedgerUpsertOne {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.AddDelta(v)
	})
}

// UpdateDelta sets the "delta" field to the value that was provided on create.
func (u *LotteryChanceLedgerUpsertOne) UpdateDelta() *LotteryChanceLedgerUpsertOne {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.UpdateDelta()
	})
}

// SetReason sets the "reason" field.
func (u *LotteryChanceLedgerUpsertOne) SetReason(v string) *LotteryChanceLedgerUpsertOne {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *LotteryChanceLedgerUpsertOne) UpdateReason() *LotteryChanceLedgerUpsertOne {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.UpdateReason()
	})
}

// SetSourceRedeemCodeID sets the "source_redeem_code_id" field.
func (u *LotteryChanceLedgerUpsertOne) SetSourceRedeemCodeID(v int64) *LotteryChanceLedgerUpsertOne {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.SetSourceRedeemCodeID(v)
	})
}

// AddSourceRedeemCodeID adds v to the "source_redeem_code_id" field.
func (u *LotteryChanceLedgerUpsertOne) AddSourceRedeemCodeID(v int64) *LotteryChanceLedgerUpsertOne {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.AddSourceRedeemCodeID(v)
	})
}

// UpdateSourceRedeemCodeID sets the "source_redeem_code_id" field to the value that was provided on create.
func (u *LotteryChanceLedgerUpsertOne) UpdateSourceRedeemCodeID() *LotteryChanceLedgerUpsertOne {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.UpdateSourceRedeemCodeID()
	})
}

// ClearSourceRedeemCodeID clears the value of the "source_redeem_code_id" field.
func (u *LotteryChanceLedgerUpsertOne) ClearSourceRedeemCodeID() *LotteryChanceLedgerUpsertOne {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.ClearSourceRedeemCodeID()
	})
}

// SetDrawRecordID sets the "draw_record_id" field.
func (u *LotteryChanceLedgerUpsertOne) SetDrawRecordID(v int64) *LotteryChanceLedgerUpsertOne {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.SetDrawRecordID(v)
	})
}

// AddDrawRecordID adds v to the "draw_record_id" field.
func (u *LotteryChanceLedgerUpsertOne) AddDrawRecordID(v int64) *LotteryChanceLedgerUpsertOne {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.AddDrawRecordID(v)
	})
}

// UpdateDrawRecordID sets the "draw_record_id" field to the value that was provided on create.
func (u *LotteryChanceLedgerUpsertOne) UpdateDrawRecordID() *LotteryChanceLedgerUpsertOne {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.UpdateDrawRecordID()
	})
}

// ClearDrawRecordID clears the value of the "draw_record_id" field.
func (u *LotteryChanceLedgerUpsertOne) ClearDrawRecordID() *LotteryChanceLedgerUpsertOne {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.ClearDrawRecordID()
	})
}

// Exec executes the query.
func (u *LotteryChanceLedgerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryChanceLedgerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryChanceLedgerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryChanceLedgerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryChanceLedgerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryChanceLedgerCreateBulk is the builder for creating many LotteryChanceLedger entities in bulk.
type LotteryChanceLedgerCreateBulk struct {
	config
	err      error
	builders []*LotteryChanceLedgerCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryChanceLedger entities in the database.
func (_c *LotteryChanceLedgerCreateBulk) Save(ctx context.Context) ([]*LotteryChanceLedger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryChanceLedger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryChanceLedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryChanceLedgerCreateBulk) SaveX(ctx context.Context) []*LotteryChanceLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryChanceLedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryChanceLedgerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryChanceLedger.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryChanceLedgerUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryChanceLedgerCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryChanceLedgerUpsertBulk {
	_c.conflict = opts
	return &LotteryChanceLedgerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryChanceLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryChanceLedgerCreateBulk) OnConflictColumns(columns ...string) *LotteryChanceLedgerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryChanceLedgerUpsertBulk{
		create: _c,
	}
}

// LotteryChanceLedgerUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryChanceLedger nodes.
type LotteryChanceLedgerUpsertBulk struct {
	create *LotteryChanceLedgerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryChanceLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryChanceLedgerUpsertBulk) UpdateNewValues() *LotteryChanceLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotterychanceledger.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryChanceLedger.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryChanceLedgerUpsertBulk) Ignore() *LotteryChanceLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryChanceLedgerUpsertBulk) DoNothing() *LotteryChanceLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryChanceLedgerCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryChanceLedgerUpsertBulk) Update(set func(*LotteryChanceLedgerUpsert)) *LotteryChanceLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryChanceLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *LotteryChanceLedgerUpsertBulk) SetUserID(v int64) *LotteryChanceLedgerUpsertBulk {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryChanceLedgerUpsertBulk) AddUserID(v int64) *LotteryChanceLedgerUpsertBulk {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryChanceLedgerUpsertBulk) UpdateUserID() *LotteryChanceLedgerUpsertBulk {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.UpdateUserID()
	})
}

// SetDelta sets the "delta" field.
func (u *LotteryChanceLedgerUpsertBulk) SetDelta(v int) *LotteryChanceLedgerUpsertBulk {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.SetDelta(v)
	})
}

// AddDelta adds v to the "delta" field.
func (u *LotteryChanceLedgerUpsertBulk) AddDelta(v int) *LotteryChanceLedgerUpsertBulk {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.AddDelta(v)
	})
}

// UpdateDelta sets the "delta" field to the value that was provided on create.
func (u *LotteryChanceLedgerUpsertBulk) UpdateDelta() *LotteryChanceLedgerUpsertBulk {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.UpdateDelta()
	})
}

// SetReason sets the "reason" field.
func (u *LotteryChanceLedgerUpsertBulk) SetReason(v string) *LotteryChanceLedgerUpsertBulk {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *LotteryChanceLedgerUpsertBulk) UpdateReason() *LotteryChanceLedgerUpsertBulk {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.UpdateReason()
	})
}

// SetSourceRedeemCodeID sets the "source_redeem_code_id" field.
func (u *LotteryChanceLedgerUpsertBulk) SetSourceRedeemCodeID(v int64) *LotteryChanceLedgerUpsertBulk {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.SetSourceRedeemCodeID(v)
	})
}

// AddSourceRedeemCodeID adds v to the "source_redeem_code_id" field.
func (u *LotteryChanceLedgerUpsertBulk) AddSourceRedeemCodeID(v int64) *LotteryChanceLedgerUpsertBulk {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.AddSourceRedeemCodeID(v)
	})
}

// UpdateSourceRedeemCodeID sets the "source_redeem_code_id" field to the value that was provided on create.
func (u *LotteryChanceLedgerUpsertBulk) UpdateSourceRedeemCodeID() *LotteryChanceLedgerUpsertBulk {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.UpdateSourceRedeemCodeID()
	})
}

// ClearSourceRedeemCodeID clears the value of the "source_redeem_code_id" field.
func (u *LotteryChanceLedgerUpsertBulk) ClearSourceRedeemCodeID() *LotteryChanceLedgerUpsertBulk {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.ClearSourceRedeemCodeID()
	})
}

// SetDrawRecordID sets the "draw_record_id" field.
func (u *LotteryChanceLedgerUpsertBulk) SetDrawRecordID(v int64) *LotteryChanceLedgerUpsertBulk {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.SetDrawRecordID(v)
	})
}

// AddDrawRecordID adds v to the "draw_record_id" field.
func (u *LotteryChanceLedgerUpsertBulk) AddDrawRecordID(v int64) *LotteryChanceLedgerUpsertBulk {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.AddDrawRecordID(v)
	})
}

// UpdateDrawRecordID sets the "draw_record_id" field to the value that was provided on create.
func (u *LotteryChanceLedgerUpsertBulk) UpdateDrawRecordID() *LotteryChanceLedgerUpsertBulk {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.UpdateDrawRecordID()
	})
}

// ClearDrawRecordID clears the value of the "draw_record_id" field.
func (u *LotteryChanceLedgerUpsertBulk) ClearDrawRecordID() *LotteryChanceLedgerUpsertBulk {
	return u.Update(func(s *LotteryChanceLedgerUpsert) {
		s.ClearDrawRecordID()
	})
}

// Exec executes the query.
func (u *LotteryChanceLedgerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryChanceLedgerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryChanceLedgerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryChanceLedgerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
