// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterydrawrecord"
)

// LotteryDrawRecordCreate is the builder for creating a LotteryDrawRecord entity.
type LotteryDrawRecordCreate struct {
	config
	mutation *LotteryDrawRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *LotteryDrawRecordCreate) SetUserID(v int64) *LotteryDrawRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPrizeName sets the "prize_name" field.
func (_c *LotteryDrawRecordCreate) SetPrizeName(v string) *LotteryDrawRecordCreate {
	_c.mutation.SetPrizeName(v)
	return _c
}

// SetPrizeValue sets the "prize_value" field.
func (_c *LotteryDrawRecordCreate) SetPrizeValue(v float64) *LotteryDrawRecordCreate {
	_c.mutation.SetPrizeValue(v)
	return _c
}

// SetPrizePoolCodeID sets the "prize_pool_code_id" field.
func (_c *LotteryDrawRecordCreate) SetPrizePoolCodeID(v int64) *LotteryDrawRecordCreate {
	_c.mutation.SetPrizePoolCodeID(v)
	return _c
}

// SetPrizeRedeemCodeID sets the "prize_redeem_code_id" field.
func (_c *LotteryDrawRecordCreate) SetPrizeRedeemCodeID(v int64) *LotteryDrawRecordCreate {
	_c.mutation.SetPrizeRedeemCodeID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryDrawRecordCreate) SetCreatedAt(v time.Time) *LotteryDrawRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryDrawRecordCreate) SetNillableCreatedAt(v *time.Time) *LotteryDrawRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the LotteryDrawRecordMutation object of the builder.
func (_c *LotteryDrawRecordCreate) Mutation() *LotteryDrawRecordMutation {
	return _c.mutation
}

// Save creates the LotteryDrawRecord in the database.
func (_c *LotteryDrawRecordCreate) Save(ctx context.Context) (*LotteryDrawRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryDrawRecordCreate) SaveX(ctx context.Context) *LotteryDrawRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryDrawRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryDrawRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryDrawRecordCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotterydrawrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryDrawRecordCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "LotteryDrawRecord.user_id"`)}
	}
	if _, ok := _c.mutation.PrizeName(); !ok {
		return &ValidationError{Name: "prize_name", err: errors.New(`ent: missing required field "LotteryDrawRecord.prize_name"`)}
	}
	if _, ok := _c.mutation.PrizeValue(); !ok {
		return &ValidationError{Name: "prize_value", err: errors.New(`ent: missing required field "LotteryDrawRecord.prize_value"`)}
	}
	if _, ok := _c.mutation.PrizePoolCodeID(); !ok {
		return &ValidationError{Name: "prize_pool_code_id", err: errors.New(`ent: missing required field "LotteryDrawRecord.prize_pool_code_id"`)}
	}
	if _, ok := _c.mutation.PrizeRedeemCodeID(); !ok {
		return &ValidationError{Name: "prize_redeem_code_id", err: errors.New(`ent: missing required field "LotteryDrawRecord.prize_redeem_code_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryDrawRecord.created_at"`)}
	}
	return nil
}

func (_c *LotteryDrawRecordCreate) sqlSave(ctx context.Context) (*LotteryDrawRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryDrawRecordCreate) createSpec() (*LotteryDrawRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryDrawRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotterydrawrecord.Table, sqlgraph.NewFieldSpec(lotterydrawrecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(lotterydrawrecord.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.PrizeName(); ok {
		_spec.SetField(lotterydrawrecord.FieldPrizeName, field.TypeString, value)
		_node.PrizeName = value
	}
	if value, ok := _c.mutation.PrizeValue(); ok {
		_spec.SetField(lotterydrawrecord.FieldPrizeValue, field.TypeFloat64, value)
		_node.PrizeValue = value
	}
	if value, ok := _c.mutation.PrizePoolCodeID(); ok {
		_spec.SetField(lotterydrawrecord.FieldPrizePoolCodeID, field.TypeInt64, value)
		_node.PrizePoolCodeID = value
	}
	if value, ok := _c.mutation.PrizeRedeemCodeID(); ok {
		_spec.SetField(lotterydrawrecord.FieldPrizeRedeemCodeID, field.TypeInt64, value)
		_node.PrizeRedeemCodeID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotterydrawrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryDrawRecord.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryDrawRecordUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryDrawRecordCreate) OnConflict(opts ...sql.ConflictOption) *LotteryDrawRecordUpsertOne {
	_c.conflict = opts
	return &LotteryDrawRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryDrawRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryDrawRecordCreate) OnConflictColumns(columns ...string) *LotteryDrawRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryDrawRecordUpsertOne{
		create: _c,
	}
}

type (
	// LotteryDrawRecordUpsertOne is the builder for "upsert"-ing
	//  one LotteryDrawRecord node.
	LotteryDrawRecordUpsertOne struct {
		create *LotteryDrawRecordCreate
	}

	// LotteryDrawRecordUpsert is the "OnConflict" setter.
	LotteryDrawRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *LotteryDrawRecordUpsert) SetUserID(v int64) *LotteryDrawRecordUpsert {
	u.Set(lotterydrawrecord.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsert) UpdateUserID() *LotteryDrawRecordUpsert {
	u.SetExcluded(lotterydrawrecord.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryDrawRecordUpsert) AddUserID(v int64) *LotteryDrawRecordUpsert {
	u.Add(lotterydrawrecord.FieldUserID, v)
	return u
}

// SetPrizeName sets the "prize_name" field.
func (u *LotteryDrawRecordUpsert) SetPrizeName(v string) *LotteryDrawRecordUpsert {
	u.Set(lotterydrawrecord.FieldPrizeName, v)
	return u
}

// UpdatePrizeName sets the "prize_name" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsert) UpdatePrizeName() *LotteryDrawRecordUpsert {
	u.SetExcluded(lotterydrawrecord.FieldPrizeName)
	return u
}

// SetPrizeValue sets the "prize_value" field.
func (u *LotteryDrawRecordUpsert) SetPrizeValue(v float64) *LotteryDrawRecordUpsert {
	u.Set(lotterydrawrecord.FieldPrizeValue, v)
	return u
}

// UpdatePrizeValue sets the "prize_value" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsert) UpdatePrizeValue() *LotteryDrawRecordUpsert {
	u.SetExcluded(lotterydrawrecord.FieldPrizeValue)
	return u
}

// AddPrizeValue adds v to the "prize_value" field.
func (u *LotteryDrawRecordUpsert) AddPrizeValue(v float64) *LotteryDrawRecordUpsert {
	u.Add(lotterydrawrecord.FieldPrizeValue, v)
	return u
}

// SetPrizePoolCodeID sets the "prize_pool_code_id" field.
func (u *LotteryDrawRecordUpsert) SetPrizePoolCodeID(v int64) *LotteryDrawRecordUpsert {
	u.Set(lotterydrawrecord.FieldPrizePoolCodeID, v)
	return u
}

// UpdatePrizePoolCodeID sets the "prize_pool_code_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsert) UpdatePrizePoolCodeID() *LotteryDrawRecordUpsert {
	u.SetExcluded(lotterydrawrecord.FieldPrizePoolCodeID)
	return u
}

// AddPrizePoolCodeID adds v to the "prize_pool_code_id" field.
func (u *LotteryDrawRecordUpsert) AddPrizePoolCodeID(v int64) *LotteryDrawRecordUpsert {
	u.Add(lotterydrawrecord.FieldPrizePoolCodeID, v)
	return u
}

// SetPrizeRedeemCodeID sets the "prize_redeem_code_id" field.
func (u *LotteryDrawRecordUpsert) SetPrizeRedeemCodeID(v int64) *LotteryDrawRecordUpsert {
	u.Set(lotterydrawrecord.FieldPrizeRedeemCodeID, v)
	return u
}

// UpdatePrizeRedeemCodeID sets the "prize_redeem_code_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsert) UpdatePrizeRedeemCodeID() *LotteryDrawRecordUpsert {
	u.SetExcluded(lotterydrawrecord.FieldPrizeRedeemCodeID)
	return u
}

// AddPrizeRedeemCodeID adds v to the "prize_redeem_code_id" field.
func (u *LotteryDrawRecordUpsert) AddPrizeRedeemCodeID(v int64) *LotteryDrawRecordUpsert {
	u.Add(lotterydrawrecord.FieldPrizeRedeemCodeID, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryDrawRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryDrawRecordUpsertOne) UpdateNewValues() *LotteryDrawRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotterydrawrecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryDrawRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryDrawRecordUpsertOne) Ignore() *LotteryDrawRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryDrawRecordUpsertOne) DoNothing() *LotteryDrawRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryDrawRecordCreate.OnConflict
// documentation for more info.
func (u *LotteryDrawRecordUpsertOne) Update(set func(*LotteryDrawRecordUpsert)) *LotteryDrawRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryDrawRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *LotteryDrawRecordUpsertOne) SetUserID(v int64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryDrawRecordUpsertOne) AddUserID(v int64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertOne) UpdateUserID() *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetPrizeName sets the "prize_name" field.
func (u *LotteryDrawRecordUpsertOne) SetPrizeName(v string) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetPrizeName(v)
	})
}

// UpdatePrizeName sets the "prize_name" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertOne) UpdatePrizeName() *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdatePrizeName()
	})
}

// SetPrizeValue sets the "prize_value" field.
func (u *LotteryDrawRecordUpsertOne) SetPrizeValue(v float64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetPrizeValue(v)
	})
}

// AddPrizeValue adds v to the "prize_value" field.
func (u *LotteryDrawRecordUpsertOne) AddPrizeValue(v float64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.AddPrizeValue(v)
	})
}

// UpdatePrizeValue sets the "prize_value" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertOne) UpdatePrizeValue() *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdatePrizeValue()
	})
}

// SetPrizePoolCodeID sets the "prize_pool_code_id" field.
func (u *LotteryDrawRecordUpsertOne) SetPrizePoolCodeID(v int64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetPrizePoolCodeID(v)
	})
}

// AddPrizePoolCodeID adds v to the "prize_pool_code_id" field.
func (u *LotteryDrawRecordUpsertOne) AddPrizePoolCodeID(v int64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.AddPrizePoolCodeID(v)
	})
}

// UpdatePrizePoolCodeID sets the "prize_pool_code_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertOne) UpdatePrizePoolCodeID() *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdatePrizePoolCodeID()
	})
}

// SetPrizeRedeemCodeID sets the "prize_redeem_code_id" field.
func (u *LotteryDrawRecordUpsertOne) SetPrizeRedeemCodeID(v int64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetPrizeRedeemCodeID(v)
	})
}

// AddPrizeRedeemCodeID adds v to the "prize_redeem_code_id" field.
func (u *LotteryDrawRecordUpsertOne) AddPrizeRedeemCodeID(v int64) *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.AddPrizeRedeemCodeID(v)
	})
}

// UpdatePrizeRedeemCodeID sets the "prize_redeem_code_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertOne) UpdatePrizeRedeemCodeID() *LotteryDrawRecordUpsertOne {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdatePrizeRedeemCodeID()
	})
}

// Exec executes the query.
func (u *LotteryDrawRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryDrawRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryDrawRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryDrawRecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryDrawRecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryDrawRecordCreateBulk is the builder for creating many LotteryDrawRecord entities in bulk.
type LotteryDrawRecordCreateBulk struct {
	config
	err      error
	builders []*LotteryDrawRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryDrawRecord entities in the database.
func (_c *LotteryDrawRecordCreateBulk) Save(ctx context.Context) ([]*LotteryDrawRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryDrawRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryDrawRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryDrawRecordCreateBulk) SaveX(ctx context.Context) []*LotteryDrawRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryDrawRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryDrawRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryDrawRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryDrawRecordUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryDrawRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryDrawRecordUpsertBulk {
	_c.conflict = opts
	return &LotteryDrawRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryDrawRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryDrawRecordCreateBulk) OnConflictColumns(columns ...string) *LotteryDrawRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryDrawRecordUpsertBulk{
		create: _c,
	}
}

// LotteryDrawRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryDrawRecord nodes.
type LotteryDrawRecordUpsertBulk struct {
	create *LotteryDrawRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryDrawRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryDrawRecordUpsertBulk) UpdateNewValues() *LotteryDrawRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotterydrawrecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryDrawRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryDrawRecordUpsertBulk) Ignore() *LotteryDrawRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryDrawRecordUpsertBulk) DoNothing() *LotteryDrawRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryDrawRecordCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryDrawRecordUpsertBulk) Update(set func(*LotteryDrawRecordUpsert)) *LotteryDrawRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryDrawRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *LotteryDrawRecordUpsertBulk) SetUserID(v int64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryDrawRecordUpsertBulk) AddUserID(v int64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertBulk) UpdateUserID() *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetPrizeName sets the "prize_name" field.
func (u *LotteryDrawRecordUpsertBulk) SetPrizeName(v string) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetPrizeName(v)
	})
}

// UpdatePrizeName sets the "prize_name" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertBulk) UpdatePrizeName() *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdatePrizeName()
	})
}

// SetPrizeValue sets the "prize_value" field.
func (u *LotteryDrawRecordUpsertBulk) SetPrizeValue(v float64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetPrizeValue(v)
	})
}

// AddPrizeValue adds v to the "prize_value" field.
func (u *LotteryDrawRecordUpsertBulk) AddPrizeValue(v float64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.AddPrizeValue(v)
	})
}

// UpdatePrizeValue sets the "prize_value" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertBulk) UpdatePrizeValue() *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdatePrizeValue()
	})
}

// SetPrizePoolCodeID sets the "prize_pool_code_id" field.
func (u *LotteryDrawRecordUpsertBulk) SetPrizePoolCodeID(v int64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetPrizePoolCodeID(v)
	})
}

// AddPrizePoolCodeID adds v to the "prize_pool_code_id" field.
func (u *LotteryDrawRecordUpsertBulk) AddPrizePoolCodeID(v int64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.AddPrizePoolCodeID(v)
	})
}

// UpdatePrizePoolCodeID sets the "prize_pool_code_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertBulk) UpdatePrizePoolCodeID() *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdatePrizePoolCodeID()
	})
}

// SetPrizeRedeemCodeID sets the "prize_redeem_code_id" field.
func (u *LotteryDrawRecordUpsertBulk) SetPrizeRedeemCodeID(v int64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.SetPrizeRedeemCodeID(v)
	})
}

// AddPrizeRedeemCodeID adds v to the "prize_redeem_code_id" field.
func (u *LotteryDrawRecordUpsertBulk) AddPrizeRedeemCodeID(v int64) *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.AddPrizeRedeemCodeID(v)
	})
}

// UpdatePrizeRedeemCodeID sets the "prize_redeem_code_id" field to the value that was provided on create.
func (u *LotteryDrawRecordUpsertBulk) UpdatePrizeRedeemCodeID() *LotteryDrawRecordUpsertBulk {
	return u.Update(func(s *LotteryDrawRecordUpsert) {
		s.UpdatePrizeRedeemCodeID()
	})
}

// Exec executes the query.
func (u *LotteryDrawRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryDrawRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryDrawRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryDrawRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
