// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterydrawrecord"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryDrawRecordUpdate is the builder for updating LotteryDrawRecord entities.
type LotteryDrawRecordUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryDrawRecordMutation
}

// Where appends a list predicates to the LotteryDrawRecordUpdate builder.
func (_u *LotteryDrawRecordUpdate) Where(ps ...predicate.LotteryDrawRecord) *LotteryDrawRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LotteryDrawRecordUpdate) SetUserID(v int64) *LotteryDrawRecordUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdate) SetNillableUserID(v *int64) *LotteryDrawRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LotteryDrawRecordUpdate) AddUserID(v int64) *LotteryDrawRecordUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPrizeName sets the "prize_name" field.
func (_u *LotteryDrawRecordUpdate) SetPrizeName(v string) *LotteryDrawRecordUpdate {
	_u.mutation.SetPrizeName(v)
	return _u
}

// SetNillablePrizeName sets the "prize_name" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdate) SetNillablePrizeName(v *string) *LotteryDrawRecordUpdate {
	if v != nil {
		_u.SetPrizeName(*v)
	}
	return _u
}

// SetPrizeValue sets the "prize_value" field.
func (_u *LotteryDrawRecordUpdate) SetPrizeValue(v float64) *LotteryDrawRecordUpdate {
	_u.mutation.ResetPrizeValue()
	_u.mutation.SetPrizeValue(v)
	return _u
}

// SetNillablePrizeValue sets the "prize_value" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdate) SetNillablePrizeValue(v *float64) *LotteryDrawRecordUpdate {
	if v != nil {
		_u.SetPrizeValue(*v)
	}
	return _u
}

// AddPrizeValue adds value to the "prize_value" field.
func (_u *LotteryDrawRecordUpdate) AddPrizeValue(v float64) *LotteryDrawRecordUpdate {
	_u.mutation.AddPrizeValue(v)
	return _u
}

// SetPrizePoolCodeID sets the "prize_pool_code_id" field.
func (_u *LotteryDrawRecordUpdate) SetPrizePoolCodeID(v int64) *LotteryDrawRecordUpdate {
	_u.mutation.ResetPrizePoolCodeID()
	_u.mutation.SetPrizePoolCodeID(v)
	return _u
}

// SetNillablePrizePoolCodeID sets the "prize_pool_code_id" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdate) SetNillablePrizePoolCodeID(v *int64) *LotteryDrawRecordUpdate {
	if v != nil {
		_u.SetPrizePoolCodeID(*v)
	}
	return _u
}

// AddPrizePoolCodeID adds value to the "prize_pool_code_id" field.
func (_u *LotteryDrawRecordUpdate) AddPrizePoolCodeID(v int64) *LotteryDrawRecordUpdate {
	_u.mutation.AddPrizePoolCodeID(v)
	return _u
}

// SetPrizeRedeemCodeID sets the "prize_redeem_code_id" field.
func (_u *LotteryDrawRecordUpdate) SetPrizeRedeemCodeID(v int64) *LotteryDrawRecordUpdate {
	_u.mutation.ResetPrizeRedeemCodeID()
	_u.mutation.SetPrizeRedeemCodeID(v)
	return _u
}

// SetNillablePrizeRedeemCodeID sets the "prize_redeem_code_id" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdate) SetNillablePrizeRedeemCodeID(v *int64) *LotteryDrawRecordUpdate {
	if v != nil {
		_u.SetPrizeRedeemCodeID(*v)
	}
	return _u
}

// AddPrizeRedeemCodeID adds value to the "prize_redeem_code_id" field.
func (_u *LotteryDrawRecordUpdate) AddPrizeRedeemCodeID(v int64) *LotteryDrawRecordUpdate {
	_u.mutation.AddPrizeRedeemCodeID(v)
	return _u
}

// Mutation returns the LotteryDrawRecordMutation object of the builder.
func (_u *LotteryDrawRecordUpdate) Mutation() *LotteryDrawRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryDrawRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryDrawRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryDrawRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryDrawRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LotteryDrawRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(lotterydrawrecord.Table, lotterydrawrecord.Columns, sqlgraph.NewFieldSpec(lotterydrawrecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(lotterydrawrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(lotterydrawrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PrizeName(); ok {
		_spec.SetField(lotterydrawrecord.FieldPrizeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrizeValue(); ok {
		_spec.SetField(lotterydrawrecord.FieldPrizeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrizeValue(); ok {
		_spec.AddField(lotterydrawrecord.FieldPrizeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PrizePoolCodeID(); ok {
		_spec.SetField(lotterydrawrecord.FieldPrizePoolCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrizePoolCodeID(); ok {
		_spec.AddField(lotterydrawrecord.FieldPrizePoolCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PrizeRedeemCodeID(); ok {
		_spec.SetField(lotterydrawrecord.FieldPrizeRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrizeRedeemCodeID(); ok {
		_spec.AddField(lotterydrawrecord.FieldPrizeRedeemCodeID, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterydrawrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryDrawRecordUpdateOne is the builder for updating a single LotteryDrawRecord entity.
type LotteryDrawRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryDrawRecordMutation
}

// SetUserID sets the "user_id" field.
func (_u *LotteryDrawRecordUpdateOne) SetUserID(v int64) *LotteryDrawRecordUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdateOne) SetNillableUserID(v *int64) *LotteryDrawRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LotteryDrawRecordUpdateOne) AddUserID(v int64) *LotteryDrawRecordUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPrizeName sets the "prize_name" field.
func (_u *LotteryDrawRecordUpdateOne) SetPrizeName(v string) *LotteryDrawRecordUpdateOne {
	_u.mutation.SetPrizeName(v)
	return _u
}

// SetNillablePrizeName sets the "prize_name" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdateOne) SetNillablePrizeName(v *string) *LotteryDrawRecordUpdateOne {
	if v != nil {
		_u.SetPrizeName(*v)
	}
	return _u
}

// SetPrizeValue sets the "prize_value" field.
func (_u *LotteryDrawRecordUpdateOne) SetPrizeValue(v float64) *LotteryDrawRecordUpdateOne {
	_u.mutation.ResetPrizeValue()
	_u.mutation.SetPrizeValue(v)
	return _u
}

// SetNillablePrizeValue sets the "prize_value" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdateOne) SetNillablePrizeValue(v *float64) *LotteryDrawRecordUpdateOne {
	if v != nil {
		_u.SetPrizeValue(*v)
	}
	return _u
}

// AddPrizeValue adds value to the "prize_value" field.
func (_u *LotteryDrawRecordUpdateOne) AddPrizeValue(v float64) *LotteryDrawRecordUpdateOne {
	_u.mutation.AddPrizeValue(v)
	return _u
}

// SetPrizePoolCodeID sets the "prize_pool_code_id" field.
func (_u *LotteryDrawRecordUpdateOne) SetPrizePoolCodeID(v int64) *LotteryDrawRecordUpdateOne {
	_u.mutation.ResetPrizePoolCodeID()
	_u.mutation.SetPrizePoolCodeID(v)
	return _u
}

// SetNillablePrizePoolCodeID sets the "prize_pool_code_id" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdateOne) SetNillablePrizePoolCodeID(v *int64) *LotteryDrawRecordUpdateOne {
	if v != nil {
		_u.SetPrizePoolCodeID(*v)
	}
	return _u
}

// AddPrizePoolCodeID adds value to the "prize_pool_code_id" field.
func (_u *LotteryDrawRecordUpdateOne) AddPrizePoolCodeID(v int64) *LotteryDrawRecordUpdateOne {
	_u.mutation.AddPrizePoolCodeID(v)
	return _u
}

// SetPrizeRedeemCodeID sets the "prize_redeem_code_id" field.
func (_u *LotteryDrawRecordUpdateOne) SetPrizeRedeemCodeID(v int64) *LotteryDrawRecordUpdateOne {
	_u.mutation.ResetPrizeRedeemCodeID()
	_u.mutation.SetPrizeRedeemCodeID(v)
	return _u
}

// SetNillablePrizeRedeemCodeID sets the "prize_redeem_code_id" field if the given value is not nil.
func (_u *LotteryDrawRecordUpdateOne) SetNillablePrizeRedeemCodeID(v *int64) *LotteryDrawRecordUpdateOne {
	if v != nil {
		_u.SetPrizeRedeemCodeID(*v)
	}
	return _u
}

// AddPrizeRedeemCodeID adds value to the "prize_redeem_code_id" field.
func (_u *LotteryDrawRecordUpdateOne) AddPrizeRedeemCodeID(v int64) *LotteryDrawRecordUpdateOne {
	_u.mutation.AddPrizeRedeemCodeID(v)
	return _u
}

// Mutation returns the LotteryDrawRecordMutation object of the builder.
func (_u *LotteryDrawRecordUpdateOne) Mutation() *LotteryDrawRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the LotteryDrawRecordUpdate builder.
func (_u *LotteryDrawRecordUpdateOne) Where(ps ...predicate.LotteryDrawRecord) *LotteryDrawRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryDrawRecordUpdateOne) Select(field string, fields ...string) *LotteryDrawRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryDrawRecord entity.
func (_u *LotteryDrawRecordUpdateOne) Save(ctx context.Context) (*LotteryDrawRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryDrawRecordUpdateOne) SaveX(ctx context.Context) *LotteryDrawRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryDrawRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryDrawRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LotteryDrawRecordUpdateOne) sqlSave(ctx context.Context) (_node *LotteryDrawRecord, err error) {
	_spec := sqlgraph.NewUpdateSpec(lotterydrawrecord.Table, lotterydrawrecord.Columns, sqlgraph.NewFieldSpec(lotterydrawrecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryDrawRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotterydrawrecord.FieldID)
		for _, f := range fields {
			if !lotterydrawrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotterydrawrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(lotterydrawrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(lotterydrawrecord.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PrizeName(); ok {
		_spec.SetField(lotterydrawrecord.FieldPrizeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrizeValue(); ok {
		_spec.SetField(lotterydrawrecord.FieldPrizeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrizeValue(); ok {
		_spec.AddField(lotterydrawrecord.FieldPrizeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PrizePoolCodeID(); ok {
		_spec.SetField(lotterydrawrecord.FieldPrizePoolCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrizePoolCodeID(); ok {
		_spec.AddField(lotterydrawrecord.FieldPrizePoolCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PrizeRedeemCodeID(); ok {
		_spec.SetField(lotterydrawrecord.FieldPrizeRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPrizeRedeemCodeID(); ok {
		_spec.AddField(lotterydrawrecord.FieldPrizeRedeemCodeID, field.TypeInt64, value)
	}
	_node = &LotteryDrawRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterydrawrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
