// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterychanceledger"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryChanceLedgerUpdate is the builder for updating LotteryChanceLedger entities.
type LotteryChanceLedgerUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryChanceLedgerMutation
}

// Where appends a list predicates to the LotteryChanceLedgerUpdate builder.
func (_u *LotteryChanceLedgerUpdate) Where(ps ...predicate.LotteryChanceLedger) *LotteryChanceLedgerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LotteryChanceLedgerUpdate) SetUserID(v int64) *LotteryChanceLedgerUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryChanceLedgerUpdate) SetNillableUserID(v *int64) *LotteryChanceLedgerUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LotteryChanceLedgerUpdate) AddUserID(v int64) *LotteryChanceLedgerUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetDelta sets the "delta" field.
func (_u *LotteryChanceLedgerUpdate) SetDelta(v int) *LotteryChanceLedgerUpdate {
	_u.mutation.ResetDelta()
	_u.mutation.SetDelta(v)
	return _u
}

// SetNillableDelta sets the "delta" field if the given value is not nil.
func (_u *LotteryChanceLedgerUpdate) SetNillableDelta(v *int) *LotteryChanceLedgerUpdate {
	if v != nil {
		_u.SetDelta(*v)
	}
	return _u
}

// AddDelta adds value to the "delta" field.
func (_u *LotteryChanceLedgerUpdate) AddDelta(v int) *LotteryChanceLedgerUpdate {
	_u.mutation.AddDelta(v)
	return _u
}

// SetReason sets the "reason" field.
func (_u *LotteryChanceLedgerUpdate) SetReason(v string) *LotteryChanceLedgerUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *LotteryChanceLedgerUpdate) SetNillableReason(v *string) *LotteryChanceLedgerUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetSourceRedeemCodeID sets the "source_redeem_code_id" field.
func (_u *LotteryChanceLedgerUpdate) SetSourceRedeemCodeID(v int64) *LotteryChanceLedgerUpdate {
	_u.mutation.ResetSourceRedeemCodeID()
	_u.mutation.SetSourceRedeemCodeID(v)
	return _u
}

// SetNillableSourceRedeemCodeID sets the "source_redeem_code_id" field if the given value is not nil.
func (_u *LotteryChanceLedgerUpdate) SetNillableSourceRedeemCodeID(v *int64) *LotteryChanceLedgerUpdate {
	if v != nil {
		_u.SetSourceRedeemCodeID(*v)
	}
	return _u
}

// AddSourceRedeemCodeID adds value to the "source_redeem_code_id" field.
func (_u *LotteryChanceLedgerUpdate) AddSourceRedeemCodeID(v int64) *LotteryChanceLedgerUpdate {
	_u.mutation.AddSourceRedeemCodeID(v)
	return _u
}

// ClearSourceRedeemCodeID clears the value of the "source_redeem_code_id" field.
func (_u *LotteryChanceLedgerUpdate) ClearSourceRedeemCodeID() *LotteryChanceLedgerUpdate {
	_u.mutation.ClearSourceRedeemCodeID()
	return _u
}

// SetDrawRecordID sets the "draw_record_id" field.
func (_u *LotteryChanceLedgerUpdate) SetDrawRecordID(v int64) *LotteryChanceLedgerUpdate {
	_u.mutation.ResetDrawRecordID()
	_u.mutation.SetDrawRecordID(v)
	return _u
}

// SetNillableDrawRecordID sets the "draw_record_id" field if the given value is not nil.
func (_u *LotteryChanceLedgerUpdate) SetNillableDrawRecordID(v *int64) *LotteryChanceLedgerUpdate {
	if v != nil {
		_u.SetDrawRecordID(*v)
	}
	return _u
}

// AddDrawRecordID adds value to the "draw_record_id" field.
func (_u *LotteryChanceLedgerUpdate) AddDrawRecordID(v int64) *LotteryChanceLedgerUpdate {
	_u.mutation.AddDrawRecordID(v)
	return _u
}

// ClearDrawRecordID clears the value of the "draw_record_id" field.
func (_u *LotteryChanceLedgerUpdate) ClearDrawRecordID() *LotteryChanceLedgerUpdate {
	_u.mutation.ClearDrawRecordID()
	return _u
}

// Mutation returns the LotteryChanceLedgerMutation object of the builder.
func (_u *LotteryChanceLedgerUpdate) Mutation() *LotteryChanceLedgerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryChanceLedgerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryChanceLedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryChanceLedgerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryChanceLedgerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LotteryChanceLedgerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(lotterychanceledger.Table, lotterychanceledger.Columns, sqlgraph.NewFieldSpec(lotterychanceledger.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(lotterychanceledger.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(lotterychanceledger.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Delta(); ok {
		_spec.SetField(lotterychanceledger.FieldDelta, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDelta(); ok {
		_spec.AddField(lotterychanceledger.FieldDelta, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(lotterychanceledger.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceRedeemCodeID(); ok {
		_spec.SetField(lotterychanceledger.FieldSourceRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceRedeemCodeID(); ok {
		_spec.AddField(lotterychanceledger.FieldSourceRedeemCodeID, field.TypeInt64, value)
	}
	if _u.mutation.SourceRedeemCodeIDCleared() {
		_spec.ClearField(lotterychanceledger.FieldSourceRedeemCodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.DrawRecordID(); ok {
		_spec.SetField(lotterychanceledger.FieldDrawRecordID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDrawRecordID(); ok {
		_spec.AddField(lotterychanceledger.FieldDrawRecordID, field.TypeInt64, value)
	}
	if _u.mutation.DrawRecordIDCleared() {
		_spec.ClearField(lotterychanceledger.FieldDrawRecordID, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterychanceledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryChanceLedgerUpdateOne is the builder for updating a single LotteryChanceLedger entity.
type LotteryChanceLedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryChanceLedgerMutation
}

// SetUserID sets the "user_id" field.
func (_u *LotteryChanceLedgerUpdateOne) SetUserID(v int64) *LotteryChanceLedgerUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryChanceLedgerUpdateOne) SetNillableUserID(v *int64) *LotteryChanceLedgerUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LotteryChanceLedgerUpdateOne) AddUserID(v int64) *LotteryChanceLedgerUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetDelta sets the "delta" field.
func (_u *LotteryChanceLedgerUpdateOne) SetDelta(v int) *LotteryChanceLedgerUpdateOne {
	_u.mutation.ResetDelta()
	_u.mutation.SetDelta(v)
	return _u
}

// SetNillableDelta sets the "delta" field if the given value is not nil.
func (_u *LotteryChanceLedgerUpdateOne) SetNillableDelta(v *int) *LotteryChanceLedgerUpdateOne {
	if v != nil {
		_u.SetDelta(*v)
	}
	return _u
}

// AddDelta adds value to the "delta" field.
func (_u *LotteryChanceLedgerUpdateOne) AddDelta(v int) *LotteryChanceLedgerUpdateOne {
	_u.mutation.AddDelta(v)
	return _u
}

// SetReason sets the "reason" field.
func (_u *LotteryChanceLedgerUpdateOne) SetReason(v string) *LotteryChanceLedgerUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *LotteryChanceLedgerUpdateOne) SetNillableReason(v *string) *LotteryChanceLedgerUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetSourceRedeemCodeID sets the "source_redeem_code_id" field.
func (_u *LotteryChanceLedgerUpdateOne) SetSourceRedeemCodeID(v int64) *LotteryChanceLedgerUpdateOne {
	_u.mutation.ResetSourceRedeemCodeID()
	_u.mutation.SetSourceRedeemCodeID(v)
	return _u
}

// SetNillableSourceRedeemCodeID sets the "source_redeem_code_id" field if the given value is not nil.
func (_u *LotteryChanceLedgerUpdateOne) SetNillableSourceRedeemCodeID(v *int64) *LotteryChanceLedgerUpdateOne {
	if v != nil {
		_u.SetSourceRedeemCodeID(*v)
	}
	return _u
}

// AddSourceRedeemCodeID adds value to the "source_redeem_code_id" field.
func (_u *LotteryChanceLedgerUpdateOne) AddSourceRedeemCodeID(v int64) *LotteryChanceLedgerUpdateOne {
	_u.mutation.AddSourceRedeemCodeID(v)
	return _u
}

// ClearSourceRedeemCodeID clears the value of the "source_redeem_code_id" field.
func (_u *LotteryChanceLedgerUpdateOne) ClearSourceRedeemCodeID() *LotteryChanceLedgerUpdateOne {
	_u.mutation.ClearSourceRedeemCodeID()
	return _u
}

// SetDrawRecordID sets the "draw_record_id" field.
func (_u *LotteryChanceLedgerUpdateOne) SetDrawRecordID(v int64) *LotteryChanceLedgerUpdateOne {
	_u.mutation.ResetDrawRecordID()
	_u.mutation.SetDrawRecordID(v)
	return _u
}

// SetNillableDrawRecordID sets the "draw_record_id" field if the given value is not nil.
func (_u *LotteryChanceLedgerUpdateOne) SetNillableDrawRecordID(v *int64) *LotteryChanceLedgerUpdateOne {
	if v != nil {
		_u.SetDrawRecordID(*v)
	}
	return _u
}

// AddDrawRecordID adds value to the "draw_record_id" field.
func (_u *LotteryChanceLedgerUpdateOne) AddDrawRecordID(v int64) *LotteryChanceLedgerUpdateOne {
	_u.mutation.AddDrawRecordID(v)
	return _u
}

// ClearDrawRecordID clears the value of the "draw_record_id" field.
func (_u *LotteryChanceLedgerUpdateOne) ClearDrawRecordID() *LotteryChanceLedgerUpdateOne {
	_u.mutation.ClearDrawRecordID()
	return _u
}

// Mutation returns the LotteryChanceLedgerMutation object of the builder.
func (_u *LotteryChanceLedgerUpdateOne) Mutation() *LotteryChanceLedgerMutation {
	return _u.mutation
}

// Where appends a list predicates to the LotteryChanceLedgerUpdate builder.
func (_u *LotteryChanceLedgerUpdateOne) Where(ps ...predicate.LotteryChanceLedger) *LotteryChanceLedgerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryChanceLedgerUpdateOne) Select(field string, fields ...string) *LotteryChanceLedgerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryChanceLedger entity.
func (_u *LotteryChanceLedgerUpdateOne) Save(ctx context.Context) (*LotteryChanceLedger, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryChanceLedgerUpdateOne) SaveX(ctx context.Context) *LotteryChanceLedger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryChanceLedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryChanceLedgerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LotteryChanceLedgerUpdateOne) sqlSave(ctx context.Context) (_node *LotteryChanceLedger, err error) {
	_spec := sqlgraph.NewUpdateSpec(lotterychanceledger.Table, lotterychanceledger.Columns, sqlgraph.NewFieldSpec(lotterychanceledger.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryChanceLedger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotterychanceledger.FieldID)
		for _, f := range fields {
			if !lotterychanceledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotterychanceledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(lotterychanceledger.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(lotterychanceledger.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Delta(); ok {
		_spec.SetField(lotterychanceledger.FieldDelta, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDelta(); ok {
		_spec.AddField(lotterychanceledger.FieldDelta, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(lotterychanceledger.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceRedeemCodeID(); ok {
		_spec.SetField(lotterychanceledger.FieldSourceRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceRedeemCodeID(); ok {
		_spec.AddField(lotterychanceledger.FieldSourceRedeemCodeID, field.TypeInt64, value)
	}
	if _u.mutation.SourceRedeemCodeIDCleared() {
		_spec.ClearField(lotterychanceledger.FieldSourceRedeemCodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.DrawRecordID(); ok {
		_spec.SetField(lotterychanceledger.FieldDrawRecordID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDrawRecordID(); ok {
		_spec.AddField(lotterychanceledger.FieldDrawRecordID, field.TypeInt64, value)
	}
	if _u.mutation.DrawRecordIDCleared() {
		_spec.ClearField(lotterychanceledger.FieldDrawRecordID, field.TypeInt64)
	}
	_node = &LotteryChanceLedger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterychanceledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
