// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryprizepoolcode"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryPrizePoolCodeUpdate is the builder for updating LotteryPrizePoolCode entities.
type LotteryPrizePoolCodeUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryPrizePoolCodeMutation
}

// Where appends a list predicates to the LotteryPrizePoolCodeUpdate builder.
func (_u *LotteryPrizePoolCodeUpdate) Where(ps ...predicate.LotteryPrizePoolCode) *LotteryPrizePoolCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *LotteryPrizePoolCodeUpdate) SetRedeemCodeID(v int64) *LotteryPrizePoolCodeUpdate {
	_u.mutation.ResetRedeemCodeID()
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *LotteryPrizePoolCodeUpdate) SetNillableRedeemCodeID(v *int64) *LotteryPrizePoolCodeUpdate {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// AddRedeemCodeID adds value to the "redeem_code_id" field.
func (_u *LotteryPrizePoolCodeUpdate) AddRedeemCodeID(v int64) *LotteryPrizePoolCodeUpdate {
	_u.mutation.AddRedeemCodeID(v)
	return _u
}

// SetPrizeValue sets the "prize_value" field.
func (_u *LotteryPrizePoolCodeUpdate) SetPrizeValue(v float64) *LotteryPrizePoolCodeUpdate {
	_u.mutation.ResetPrizeValue()
	_u.mutation.SetPrizeValue(v)
	return _u
}

// SetNillablePrizeValue sets the "prize_value" field if the given value is not nil.
func (_u *LotteryPrizePoolCodeUpdate) SetNillablePrizeValue(v *float64) *LotteryPrizePoolCodeUpdate {
	if v != nil {
		_u.SetPrizeValue(*v)
	}
	return _u
}

// AddPrizeValue adds value to the "prize_value" field.
func (_u *LotteryPrizePoolCodeUpdate) AddPrizeValue(v float64) *LotteryPrizePoolCodeUpdate {
	_u.mutation.AddPrizeValue(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *LotteryPrizePoolCodeUpdate) SetStatus(v string) *LotteryPrizePoolCodeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LotteryPrizePoolCodeUpdate) SetNillableStatus(v *string) *LotteryPrizePoolCodeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAssignedToUserID sets the "assigned_to_user_id" field.
func (_u *LotteryPrizePoolCodeUpdate) SetAssignedToUserID(v int64) *LotteryPrizePoolCodeUpdate {
	_u.mutation.ResetAssignedToUserID()
	_u.mutation.SetAssignedToUserID(v)
	return _u
}

// SetNillableAssignedToUserID sets the "assigned_to_user_id" field if the given value is not nil.
func (_u *LotteryPrizePoolCodeUpdate) SetNillableAssignedToUserID(v *int64) *LotteryPrizePoolCodeUpdate {
	if v != nil {
		_u.SetAssignedToUserID(*v)
	}
	return _u
}

// AddAssignedToUserID adds value to the "assigned_to_user_id" field.
func (_u *LotteryPrizePoolCodeUpdate) AddAssignedToUserID(v int64) *LotteryPrizePoolCodeUpdate {
	_u.mutation.AddAssignedToUserID(v)
	return _u
}

// ClearAssignedToUserID clears the value of the "assigned_to_user_id" field.
func (_u *LotteryPrizePoolCodeUpdate) ClearAssignedToUserID() *LotteryPrizePoolCodeUpdate {
	_u.mutation.ClearAssignedToUserID()
	return _u
}

// SetAssignedDrawRecordID sets the "assigned_draw_record_id" field.
func (_u *LotteryPrizePoolCodeUpdate) SetAssignedDrawRecordID(v int64) *LotteryPrizePoolCodeUpdate {
	_u.mutation.ResetAssignedDrawRecordID()
	_u.mutation.SetAssignedDrawRecordID(v)
	return _u
}

// SetNillableAssignedDrawRecordID sets the "assigned_draw_record_id" field if the given value is not nil.
func (_u *LotteryPrizePoolCodeUpdate) SetNillableAssignedDrawRecordID(v *int64) *LotteryPrizePoolCodeUpdate {
	if v != nil {
		_u.SetAssignedDrawRecordID(*v)
	}
	return _u
}

// AddAssignedDrawRecordID adds value to the "assigned_draw_record_id" field.
func (_u *LotteryPrizePoolCodeUpdate) AddAssignedDrawRecordID(v int64) *LotteryPrizePoolCodeUpdate {
	_u.mutation.AddAssignedDrawRecordID(v)
	return _u
}

// ClearAssignedDrawRecordID clears the value of the "assigned_draw_record_id" field.
func (_u *LotteryPrizePoolCodeUpdate) ClearAssignedDrawRecordID() *LotteryPrizePoolCodeUpdate {
	_u.mutation.ClearAssignedDrawRecordID()
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *LotteryPrizePoolCodeUpdate) SetAssignedAt(v time.Time) *LotteryPrizePoolCodeUpdate {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *LotteryPrizePoolCodeUpdate) SetNillableAssignedAt(v *time.Time) *LotteryPrizePoolCodeUpdate {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (_u *LotteryPrizePoolCodeUpdate) ClearAssignedAt() *LotteryPrizePoolCodeUpdate {
	_u.mutation.ClearAssignedAt()
	return _u
}

// Mutation returns the LotteryPrizePoolCodeMutation object of the builder.
func (_u *LotteryPrizePoolCodeUpdate) Mutation() *LotteryPrizePoolCodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryPrizePoolCodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryPrizePoolCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryPrizePoolCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryPrizePoolCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LotteryPrizePoolCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(lotteryprizepoolcode.Table, lotteryprizepoolcode.Columns, sqlgraph.NewFieldSpec(lotteryprizepoolcode.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RedeemCodeID(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRedeemCodeID(); ok {
		_spec.AddField(lotteryprizepoolcode.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PrizeValue(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldPrizeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrizeValue(); ok {
		_spec.AddField(lotteryprizepoolcode.FieldPrizeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssignedToUserID(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldAssignedToUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAssignedToUserID(); ok {
		_spec.AddField(lotteryprizepoolcode.FieldAssignedToUserID, field.TypeInt64, value)
	}
	if _u.mutation.AssignedToUserIDCleared() {
		_spec.ClearField(lotteryprizepoolcode.FieldAssignedToUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AssignedDrawRecordID(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldAssignedDrawRecordID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAssignedDrawRecordID(); ok {
		_spec.AddField(lotteryprizepoolcode.FieldAssignedDrawRecordID, field.TypeInt64, value)
	}
	if _u.mutation.AssignedDrawRecordIDCleared() {
		_spec.ClearField(lotteryprizepoolcode.FieldAssignedDrawRecordID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldAssignedAt, field.TypeTime, value)
	}
	if _u.mutation.AssignedAtCleared() {
		_spec.ClearField(lotteryprizepoolcode.FieldAssignedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotteryprizepoolcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryPrizePoolCodeUpdateOne is the builder for updating a single LotteryPrizePoolCode entity.
type LotteryPrizePoolCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryPrizePoolCodeMutation
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *LotteryPrizePoolCodeUpdateOne) SetRedeemCodeID(v int64) *LotteryPrizePoolCodeUpdateOne {
	_u.mutation.ResetRedeemCodeID()
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *LotteryPrizePoolCodeUpdateOne) SetNillableRedeemCodeID(v *int64) *LotteryPrizePoolCodeUpdateOne {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// AddRedeemCodeID adds value to the "redeem_code_id" field.
func (_u *LotteryPrizePoolCodeUpdateOne) AddRedeemCodeID(v int64) *LotteryPrizePoolCodeUpdateOne {
	_u.mutation.AddRedeemCodeID(v)
	return _u
}

// SetPrizeValue sets the "prize_value" field.
func (_u *LotteryPrizePoolCodeUpdateOne) SetPrizeValue(v float64) *LotteryPrizePoolCodeUpdateOne {
	_u.mutation.ResetPrizeValue()
	_u.mutation.SetPrizeValue(v)
	return _u
}

// SetNillablePrizeValue sets the "prize_value" field if the given value is not nil.
func (_u *LotteryPrizePoolCodeUpdateOne) SetNillablePrizeValue(v *float64) *LotteryPrizePoolCodeUpdateOne {
	if v != nil {
		_u.SetPrizeValue(*v)
	}
	return _u
}

// AddPrizeValue adds value to the "prize_value" field.
func (_u *LotteryPrizePoolCodeUpdateOne) AddPrizeValue(v float64) *LotteryPrizePoolCodeUpdateOne {
	_u.mutation.AddPrizeValue(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *LotteryPrizePoolCodeUpdateOne) SetStatus(v string) *LotteryPrizePoolCodeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LotteryPrizePoolCodeUpdateOne) SetNillableStatus(v *string) *LotteryPrizePoolCodeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAssignedToUserID sets the "assigned_to_user_id" field.
func (_u *LotteryPrizePoolCodeUpdateOne) SetAssignedToUserID(v int64) *LotteryPrizePoolCodeUpdateOne {
	_u.mutation.ResetAssignedToUserID()
	_u.mutation.SetAssignedToUserID(v)
	return _u
}

// SetNillableAssignedToUserID sets the "assigned_to_user_id" field if the given value is not nil.
func (_u *LotteryPrizePoolCodeUpdateOne) SetNillableAssignedToUserID(v *int64) *LotteryPrizePoolCodeUpdateOne {
	if v != nil {
		_u.SetAssignedToUserID(*v)
	}
	return _u
}

// AddAssignedToUserID adds value to the "assigned_to_user_id" field.
func (_u *LotteryPrizePoolCodeUpdateOne) AddAssignedToUserID(v int64) *LotteryPrizePoolCodeUpdateOne {
	_u.mutation.AddAssignedToUserID(v)
	return _u
}

// ClearAssignedToUserID clears the value of the "assigned_to_user_id" field.
func (_u *LotteryPrizePoolCodeUpdateOne) ClearAssignedToUserID() *LotteryPrizePoolCodeUpdateOne {
	_u.mutation.ClearAssignedToUserID()
	return _u
}

// SetAssignedDrawRecordID sets the "assigned_draw_record_id" field.
func (_u *LotteryPrizePoolCodeUpdateOne) SetAssignedDrawRecordID(v int64) *LotteryPrizePoolCodeUpdateOne {
	_u.mutation.ResetAssignedDrawRecordID()
	_u.mutation.SetAssignedDrawRecordID(v)
	return _u
}

// SetNillableAssignedDrawRecordID sets the "assigned_draw_record_id" field if the given value is not nil.
func (_u *LotteryPrizePoolCodeUpdateOne) SetNillableAssignedDrawRecordID(v *int64) *LotteryPrizePoolCodeUpdateOne {
	if v != nil {
		_u.SetAssignedDrawRecordID(*v)
	}
	return _u
}

// AddAssignedDrawRecordID adds value to the "assigned_draw_record_id" field.
func (_u *LotteryPrizePoolCodeUpdateOne) AddAssignedDrawRecordID(v int64) *LotteryPrizePoolCodeUpdateOne {
	_u.mutation.AddAssignedDrawRecordID(v)
	return _u
}

// ClearAssignedDrawRecordID clears the value of the "assigned_draw_record_id" field.
func (_u *LotteryPrizePoolCodeUpdateOne) ClearAssignedDrawRecordID() *LotteryPrizePoolCodeUpdateOne {
	_u.mutation.ClearAssignedDrawRecordID()
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *LotteryPrizePoolCodeUpdateOne) SetAssignedAt(v time.Time) *LotteryPrizePoolCodeUpdateOne {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *LotteryPrizePoolCodeUpdateOne) SetNillableAssignedAt(v *time.Time) *LotteryPrizePoolCodeUpdateOne {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (_u *LotteryPrizePoolCodeUpdateOne) ClearAssignedAt() *LotteryPrizePoolCodeUpdateOne {
	_u.mutation.ClearAssignedAt()
	return _u
}

// Mutation returns the LotteryPrizePoolCodeMutation object of the builder.
func (_u *LotteryPrizePoolCodeUpdateOne) Mutation() *LotteryPrizePoolCodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the LotteryPrizePoolCodeUpdate builder.
func (_u *LotteryPrizePoolCodeUpdateOne) Where(ps ...predicate.LotteryPrizePoolCode) *LotteryPrizePoolCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryPrizePoolCodeUpdateOne) Select(field string, fields ...string) *LotteryPrizePoolCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryPrizePoolCode entity.
func (_u *LotteryPrizePoolCodeUpdateOne) Save(ctx context.Context) (*LotteryPrizePoolCode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryPrizePoolCodeUpdateOne) SaveX(ctx context.Context) *LotteryPrizePoolCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryPrizePoolCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryPrizePoolCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LotteryPrizePoolCodeUpdateOne) sqlSave(ctx context.Context) (_node *LotteryPrizePoolCode, err error) {
	_spec := sqlgraph.NewUpdateSpec(lotteryprizepoolcode.Table, lotteryprizepoolcode.Columns, sqlgraph.NewFieldSpec(lotteryprizepoolcode.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryPrizePoolCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotteryprizepoolcode.FieldID)
		for _, f := range fields {
			if !lotteryprizepoolcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotteryprizepoolcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RedeemCodeID(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRedeemCodeID(); ok {
		_spec.AddField(lotteryprizepoolcode.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PrizeValue(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldPrizeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrizeValue(); ok {
		_spec.AddField(lotteryprizepoolcode.FieldPrizeValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssignedToUserID(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldAssignedToUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAssignedToUserID(); ok {
		_spec.AddField(lotteryprizepoolcode.FieldAssignedToUserID, field.TypeInt64, value)
	}
	if _u.mutation.AssignedToUserIDCleared() {
		_spec.ClearField(lotteryprizepoolcode.FieldAssignedToUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AssignedDrawRecordID(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldAssignedDrawRecordID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAssignedDrawRecordID(); ok {
		_spec.AddField(lotteryprizepoolcode.FieldAssignedDrawRecordID, field.TypeInt64, value)
	}
	if _u.mutation.AssignedDrawRecordIDCleared() {
		_spec.ClearField(lotteryprizepoolcode.FieldAssignedDrawRecordID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(lotteryprizepoolcode.FieldAssignedAt, field.TypeTime, value)
	}
	if _u.mutation.AssignedAtCleared() {
		_spec.ClearField(lotteryprizepoolcode.FieldAssignedAt, field.TypeTime)
	}
	_node = &LotteryPrizePoolCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotteryprizepoolcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
