// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterychanceledger"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryChanceLedgerDelete is the builder for deleting a LotteryChanceLedger entity.
type LotteryChanceLedgerDelete struct {
	config
	hooks    []Hook
	mutation *LotteryChanceLedgerMutation
}

// Where appends a list predicates to the LotteryChanceLedgerDelete builder.
func (_d *LotteryChanceLedgerDelete) Where(ps ...predicate.LotteryChanceLedger) *LotteryChanceLedgerDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LotteryChanceLedgerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LotteryChanceLedgerDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LotteryChanceLedgerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(lotterychanceledger.Table, sqlgraph.NewFieldSpec(lotterychanceledger.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LotteryChanceLedgerDeleteOne is the builder for deleting a single LotteryChanceLedger entity.
type LotteryChanceLedgerDeleteOne struct {
	_d *LotteryChanceLedgerDelete
}

// Where appends a list predicates to the LotteryChanceLedgerDelete builder.
func (_d *LotteryChanceLedgerDeleteOne) Where(ps ...predicate.LotteryChanceLedger) *LotteryChanceLedgerDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LotteryChanceLedgerDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{lotterychanceledger.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LotteryChanceLedgerDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
