// Code generated by ent, DO NOT EDIT.

package lotterychanceledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the lotterychanceledger type in the database.
	Label = "lottery_chance_ledger"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldDelta holds the string denoting the delta field in the database.
	FieldDelta = "delta"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldSourceRedeemCodeID holds the string denoting the source_redeem_code_id field in the database.
	FieldSourceRedeemCodeID = "source_redeem_code_id"
	// FieldDrawRecordID holds the string denoting the draw_record_id field in the database.
	FieldDrawRecordID = "draw_record_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the lotterychanceledger in the database.
	Table = "lottery_chance_ledger"
)

// Columns holds all SQL columns for lotterychanceledger fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldDelta,
	FieldReason,
	FieldSourceRedeemCodeID,
	FieldDrawRecordID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the LotteryChanceLedger queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByDelta orders the results by the delta field.
func ByDelta(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDelta, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// BySourceRedeemCodeID orders the results by the source_redeem_code_id field.
func BySourceRedeemCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceRedeemCodeID, opts...).ToFunc()
}

// ByDrawRecordID orders the results by the draw_record_id field.
func ByDrawRecordID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDrawRecordID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
