// Code generated by ent, DO NOT EDIT.

package lotterychanceledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldEQ(FieldUserID, v))
}

// Delta applies equality check predicate on the "delta" field. It's identical to DeltaEQ.
func Delta(v int) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldEQ(FieldDelta, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldEQ(FieldReason, v))
}

// SourceRedeemCodeID applies equality check predicate on the "source_redeem_code_id" field. It's identical to SourceRedeemCodeIDEQ.
func SourceRedeemCodeID(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldEQ(FieldSourceRedeemCodeID, v))
}

// DrawRecordID applies equality check predicate on the "draw_record_id" field. It's identical to DrawRecordIDEQ.
func DrawRecordID(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldEQ(FieldDrawRecordID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldLTE(FieldUserID, v))
}

// DeltaEQ applies the EQ predicate on the "delta" field.
func DeltaEQ(v int) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldEQ(FieldDelta, v))
}

// DeltaNEQ applies the NEQ predicate on the "delta" field.
func DeltaNEQ(v int) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldNEQ(FieldDelta, v))
}

// DeltaIn applies the In predicate on the "delta" field.
func DeltaIn(vs ...int) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldIn(FieldDelta, vs...))
}

// DeltaNotIn applies the NotIn predicate on the "delta" field.
func DeltaNotIn(vs ...int) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldNotIn(FieldDelta, vs...))
}

// DeltaGT applies the GT predicate on the "delta" field.
func DeltaGT(v int) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldGT(FieldDelta, v))
}

// DeltaGTE applies the GTE predicate on the "delta" field.
func DeltaGTE(v int) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldGTE(FieldDelta, v))
}

// DeltaLT applies the LT predicate on the "delta" field.
func DeltaLT(v int) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldLT(FieldDelta, v))
}

// DeltaLTE applies the LTE predicate on the "delta" field.
func DeltaLTE(v int) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldLTE(FieldDelta, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldContainsFold(FieldReason, v))
}

// SourceRedeemCodeIDEQ applies the EQ predicate on the "source_redeem_code_id" field.
func SourceRedeemCodeIDEQ(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldEQ(FieldSourceRedeemCodeID, v))
}

// SourceRedeemCodeIDNEQ applies the NEQ predicate on the "source_redeem_code_id" field.
func SourceRedeemCodeIDNEQ(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldNEQ(FieldSourceRedeemCodeID, v))
}

// SourceRedeemCodeIDIn applies the In predicate on the "source_redeem_code_id" field.
func SourceRedeemCodeIDIn(vs ...int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldIn(FieldSourceRedeemCodeID, vs...))
}

// SourceRedeemCodeIDNotIn applies the NotIn predicate on the "source_redeem_code_id" field.
func SourceRedeemCodeIDNotIn(vs ...int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldNotIn(FieldSourceRedeemCodeID, vs...))
}

// SourceRedeemCodeIDGT applies the GT predicate on the "source_redeem_code_id" field.
func SourceRedeemCodeIDGT(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldGT(FieldSourceRedeemCodeID, v))
}

// SourceRedeemCodeIDGTE applies the GTE predicate on the "source_redeem_code_id" field.
func SourceRedeemCodeIDGTE(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldGTE(FieldSourceRedeemCodeID, v))
}

// SourceRedeemCodeIDLT applies the LT predicate on the "source_redeem_code_id" field.
func SourceRedeemCodeIDLT(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldLT(FieldSourceRedeemCodeID, v))
}

// SourceRedeemCodeIDLTE applies the LTE predicate on the "source_redeem_code_id" field.
func SourceRedeemCodeIDLTE(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldLTE(FieldSourceRedeemCodeID, v))
}

// SourceRedeemCodeIDIsNil applies the IsNil predicate on the "source_redeem_code_id" field.
func SourceRedeemCodeIDIsNil() predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldIsNull(FieldSourceRedeemCodeID))
}

// SourceRedeemCodeIDNotNil applies the NotNil predicate on the "source_redeem_code_id" field.
func SourceRedeemCodeIDNotNil() predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldNotNull(FieldSourceRedeemCodeID))
}

// DrawRecordIDEQ applies the EQ predicate on the "draw_record_id" field.
func DrawRecordIDEQ(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldEQ(FieldDrawRecordID, v))
}

// DrawRecordIDNEQ applies the NEQ predicate on the "draw_record_id" field.
func DrawRecordIDNEQ(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldNEQ(FieldDrawRecordID, v))
}

// DrawRecordIDIn applies the In predicate on the "draw_record_id" field.
func DrawRecordIDIn(vs ...int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldIn(FieldDrawRecordID, vs...))
}

// DrawRecordIDNotIn applies the NotIn predicate on the "draw_record_id" field.
func DrawRecordIDNotIn(vs ...int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldNotIn(FieldDrawRecordID, vs...))
}

// DrawRecordIDGT applies the GT predicate on the "draw_record_id" field.
func DrawRecordIDGT(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldGT(FieldDrawRecordID, v))
}

// DrawRecordIDGTE applies the GTE predicate on the "draw_record_id" field.
func DrawRecordIDGTE(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldGTE(FieldDrawRecordID, v))
}

// DrawRecordIDLT applies the LT predicate on the "draw_record_id" field.
func DrawRecordIDLT(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldLT(FieldDrawRecordID, v))
}

// DrawRecordIDLTE applies the LTE predicate on the "draw_record_id" field.
func DrawRecordIDLTE(v int64) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldLTE(FieldDrawRecordID, v))
}

// DrawRecordIDIsNil applies the IsNil predicate on the "draw_record_id" field.
func DrawRecordIDIsNil() predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldIsNull(FieldDrawRecordID))
}

// DrawRecordIDNotNil applies the NotNil predicate on the "draw_record_id" field.
func DrawRecordIDNotNil() predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldNotNull(FieldDrawRecordID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LotteryChanceLedger) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LotteryChanceLedger) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LotteryChanceLedger) predicate.LotteryChanceLedger {
	return predicate.LotteryChanceLedger(sql.NotPredicates(p))
}
